In [1]:
import pandas as pd
import zipfile

In [ ]:
# without pandas
tiny_tsv_list = []

with open('tiny_tsv.tsv') as tsv_file:
    for line in tsv_file:
        tiny_tsv_list.append(line.rstrip('\n').split('\t'))

In [3]:
tiny_tsv_list

[['rank', 'name', 'test_type'],
 ['1', 'Adam', 'IQ'],
 ['2', 'Maria', 'EQ'],
 ['3', 'Jenny', 'IQ'],
 ['4', 'Amira', 'IQ'],
 ['5', 'Ola', 'EQ']]

In [ ]:
# using pandas
df = pd.read_csv('tiny_tsv.tsv',sep='\t')
df

   rank   name test_type
0     1   Adam        IQ
1     2  Maria        EQ
2     3  Jenny        IQ
3     4  Amira        IQ
4     5    Ola        EQ

In [6]:
# Reading in a zipped file

df = pd.read_csv('tiny_csv.zip')

In [7]:
# zip file read improperly
df

     rank;name;test_type
0              1;Adam;IQ
1             2;Maria;EQ
2             3;Jenny;IQ
3             4;Amira;IQ
4               5;Ola;EQ
5  6;Jerry;No Test Taken
6               7;Kai;EQ

In [8]:
# Modifying the zip file and cleaning up the df 

with zipfile.ZipFile('tiny_csv.zip',"r") as zip_ref:
    zip_ref.extractall('tiny_csv_folder/')

In [10]:
new_df = pd.read_csv('tiny_csv_folder/tiny_csv.csv')

In [11]:
new_df

     rank;name;test_type
0              1;Adam;IQ
1             2;Maria;EQ
2             3;Jenny;IQ
3             4;Amira;IQ
4               5;Ola;EQ
5  6;Jerry;No Test Taken
6               7;Kai;EQ

In [16]:
# calling params to clean up the df
new_df = pd.read_csv('tiny_csv_folder/tiny_csv.csv',
                     header=0,
                     index_col='rank',
                     sep=';',
                     dtype={"rank":'int',
                            "name":"string",
                            "type": "string"},
                    na_values="No Test Taken")

In [17]:
new_df

       name test_type
rank
1      Adam        IQ
2     Maria        EQ
3     Jenny        IQ
4     Amira        IQ
5       Ola        EQ
6     Jerry       NaN
7       Kai        EQ

### Programmatic Downloads of Data

In [18]:
import pandas as pd
import requests 
import os

In [ ]:
# creating a new directory if it doesnt exist
folder_name = 'ebert_reviews_2017'
if not os.path.exists(folder_name):
    os.makedirs(folder_name)

In [20]:
# list of URLS to get data from 
ebert_review_urls = ['https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9900_1-the-wizard-of-oz-1939-film/1-the-wizard-of-oz-1939-film.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9901_2-citizen-kane/2-citizen-kane.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/September/59ad9901_3-the-third-man/3-the-third-man.txt',
                     'https://d17h27t6h515a5.cloudfront.net/topher/2017/SeptemberBumblebee/59ad9901_3-the-third-man/3-the-third-man.txt']

In [21]:
for url in ebert_review_urls:
    #Create an HTTP GET request for Ebert reviews
    response = requests.get(url)
    #Raise an exception if we made a request resulting in an error
    response.raise_for_status()
    #Define the filepath by incorporating the folder_name and the last part of the url
    file_path = os.path.join(folder_name, url.split('/')[-1])
    print(file_path)
    #Writing in binary mode
    with open(file_path, mode = 'wb') as file:
        file.write(response.content)

ebert_reviews_2017\1-the-wizard-of-oz-1939-film.txt
ebert_reviews_2017\2-citizen-kane.txt
ebert_reviews_2017\3-the-third-man.txt

HTTPError: 403 Client Error: Forbidden for url: https://d17h27t6h515a5.cloudfront.net/topher/2017/SeptemberBumblebee/59ad9901_3-the-third-man/3-the-third-man.txt

Could not get data from 4th URL - 403 error raised

In [22]:
# Listing files for directory
os.listdir(folder_name)

['1-the-wizard-of-oz-1939-film.txt',
 '2-citizen-kane.txt',
 '3-the-third-man.txt']

In [ ]:
# checking data retrieved with magic keyword below 
# %load ebert_reviews_2017/3-the-third-man.txt
The Third Man (1949)
http://www.rogerebert.com/reviews/great-movie-the-third-man-1949
Has there ever been a film where the music more perfectly suited the action than in Carol Reed's "The Third Man"? The score was performed on a zither by Anton Karas, who was playing in a Vienna beerhouse one night when Reed heard him. The sound is jaunty but without joy, like whistling in the dark. It sets the tone; the action begins like an undergraduate lark and then reveals vicious undertones.

The story begins with a spoken prologue ("I never knew the old Vienna, before the war. . ."). The shattered postwar city has been divided into French, American, British and Russian zones, each with its own cadre of suspicious officials. Into this sinkhole of intrigue falls an American innocent: Holly Martins (Joseph Cotton), alcoholic author of pulp Westerns. He has come at the invitation of his college chum Harry Lime. But Lime is being buried when Martins arrives in Vienna.

How did Lime die? That question is the engine that drives the plot, as Martins plunges into the murk that Lime left behind. Calloway (Trevor Howard), the British officer in charge, bluntly says Lime was an evil man, and advises Holly to take the next train home. But Harry had a girl named Anna (Alida Valli), who Holly sees at Lime's grave, and perhaps she has some answers. Certainly Holly has fallen in love with her, although his trusting Yankee heart is no match for her defenses.

"The Third Man" (1949) was made by men who knew the devastation of Europe at first hand. Carol Reed worked for the British Army's wartime documentary unit, and the screenplay was by Graham Greene, who not only wrote about spies but occasionally acted as one. Reed fought with David O. Selznick, his American producer, over every detail of the movie; Selznick wanted to shoot on sets, use an upbeat score and cast Noel Coward as Harry Lime. His film would have been forgotten in a week. Reed defied convention by shooting entirely on location in Vienna, where mountains of rubble stood next to gaping bomb craters, and the ruins of empire supported a desperate black market economy. And he insisted on Karas' zither music ("The Third Man Theme" was one of 1950's biggest hits).

Reed and his Academy Award-winning cinematographer, Robert Krasker, also devised a reckless, unforgettable visual style. More shots, I suspect, are tilted than are held straight; they suggest a world out of joint. There are fantastic oblique angles. Wide-angle lenses distort faces and locations. And the bizarre lighting makes the city into an expressionist nightmare. (During a stakeout for Lime, a little balloon man wanders onto the scene, and his shadow is a monster three stories high). Vienna in "The Third Man" is a more particular and unmistakable *place* than almost any other location in the history of the movies; the action fits the city like a hand slipping on a glove.

Then there are the faces: Joseph Cotton's open, naive face contrasts with the "friends" of Harry Lime: the corrupt "Baron" Kurtz (Ernst Deutsch); the shifty Dr. Winkel (Erich Ponto), the ratlike Popescu (Siegfried Breuer). Even a little boy with a rubber ball looks like a wizened imp. The only trusting faces are those of innocents like the hall porter (Paul Hoerbiger) who tells Holly, "There was another man . . . a third man. . ." and the beefy Sgt. Paine (Bernard Lee), Calloway's aide, who levels the drunken Holly with a shot to the chin and then apologizes. Even the resident exiles are corrupt; Crabbin (Wilfrid Hyde-White), the head of the discussion group, chatters about culture while smoothly maneuvering his mistress out of sight through doors and up stairs.

As for Harry Lime: He allows Orson Welles to make the most famous entrance in the history of the movies, and one of the most famous speeches. By the time Lime finally appears we have almost forgotten Welles is even *in* the movie. The sequence is unforgettable: the meow of the cat in the doorway, the big shoes, the defiant challenge by Holly, the light in the window, and then the shot, pushing in, on Lime's face, enigmatic and teasing, as if two college chums had been caught playing a naughty prank.

The famous speech comes during an uneasy ride on a giant Ferris wheel; at one point, Lime slides open the door of the car they are riding in, and Holly uneasily wraps an arm around a post. Harry tries to justify himself: "You know what the fellow said: In Italy for 30 years under the Borgias they had warfare, terror, murder and bloodshed, but they produced Michelangelo, Leonardo da Vinci and the Renaissance. In Switzerland they had brotherly love--they had 500 years of democracy and peace, and what did that produce? The cuckoo clock." (Greene says this speech was written by Welles.)

The emotional heart of the movie is Holly's infatuation with Anna, who will love Harry and be grateful to him no matter what she learns. The scenes between Holly and Anna are enriched by tiny details, as when they visit Harry's apartment and she opens a drawer without looking--because she already knows what will be inside. Or the way she sometimes slips and calls Holly "Harry." Everyone in the movie has trouble with names. Holly calls Calloway "Callahan," and Dr. Winkle insists on "VINK-ell!" And the name on Harry Lime's tombstone is wrong, too.

The chase sequence in "The Third Man" is another joining of the right action with the right location. Harry escapes into the sewer system like a cornered rat, and Reed edits the pursuit into long, echoing, empty sewer vistas, and closeups of Lime's sweaty face, his eyes darting for a way out. Presumably there would be no lights in the Vienna sewers, but there are strong light sources just out of sight behind every corner, throwing elongated shadows, backlighting Harry and his pursuers.

The final scene in "The Third Man" is a long, elegiac sigh. It almost did not exist. Selznick and Greene originally wanted a happy ending. (Greene originally wrote, ". . . her hand was through his arm"). Reed convinced Greene he was wrong. The movie ends as it begins, in a cemetery, and then Calloway gives Holly a ride back to town. They pass Anna walking on the roadside. Holly asks to be let out of the jeep. He stands under a tree, waiting for her. She walks toward him, past him, and then out of frame, never looking. After a long pause, Holly lights a cigarette and wearily throws away the match. Joseph Cotten recalled later that he thought the scene would end sooner. But Reed kept the camera running, making it an unusually long shot, and absolutely perfect.

"The Third Man" reflects the optimism of Americans and the bone-weariness of Europe after the war. It's a story about grownups and children: Adults like Calloway, who has seen at first hand the results of Lime's crimes, and children like the trusting Holly, who believes in the simplified good and evil of his Western novels.

"The Third Man" is like the exhausted aftermath of "Casablanca." Both have heroes who are American exiles, awash in a world of treachery and black market intrigue. Both heroes love a woman battered by the war. But "Casablanca" is bathed in the hope of victory, while "The Third Man" already reflects the Cold War years of paranoia, betrayal and the Bomb. The hero doesn't get the girl in either movie--but in "Casablanca," Ilsa stays with the resistance leader to help in his fight, while in "The Third Man" Anna remains loyal to a rat. Yet Harry Lime saved Anna, a displaced person who faced certain death. Holly will never understand what Anna did to survive the war, and Anna has absolutely no desire to tell him.

Of all the movies I have seen, this one most completely embodies the romance of going to the movies. I saw it first on a rainy day in a tiny, smoke-filled cinema on the Left Bank in Paris. It told a story of existential loss and betrayal. It was weary and knowing, and its glorious style was an act of defiance against the corrupt world it pictured. Seeing it, I realized how many Hollywood movies were like the pulp Westerns that Holly Martins wrote: naive formulas supplying happy endings for passive consumption. I read the other day that they plan to remake "The Third Man." Do you think Anna will cave in to Holly--or will she remain true to her bitter cynicism and unspeakable knowledge?

### Glob and Text Files

In [25]:
import glob
import pandas as pd

In [ ]:
# All txt files in dir
glob.glob('ebert_reviews_2017/*.txt')

['ebert_reviews_2017\\1-the-wizard-of-oz-1939-film.txt',
 'ebert_reviews_2017\\2-citizen-kane.txt',
 'ebert_reviews_2017\\3-the-third-man.txt']

In [27]:
text_list = []
#Iterate through files in directory
for ebert_review in glob.glob('ebert_reviews_2017/*.txt'):
    #Open file with UTF-8 encoding
    with open(ebert_review, encoding='utf-8') as file:
        #Read the 1st line
        title = file.readline()[:-1]
        #Read the 2nd line
        review_url = file.readline()[:-1]
        review_text = file.read()
        # Append to list of dictionaries
        text_list.append({'title': title,
                        'review_url': review_url,
                        'review_text': review_text})
#Convert list of dictionaries to Dataframe
df = pd.DataFrame(text_list, columns = ['title', 'review_url', 'review_text'])

In [28]:
df.head()

,title,review_url,review_text
0,The Wizard of Oz (1939),http://www.rogerebert.com/reviews/great-movie-...,As a child I simply did not notice whether a m...
1,Citizen Kane (1941),http://www.rogerebert.com/reviews/great-movie-...,“I don't think any word can explain a man's li...
2,The Third Man (1949),http://www.rogerebert.com/reviews/great-movie-...,Has there ever been a film where the music mor...

### JSON and API's

In [29]:
import json
import requests

In [30]:
book = requests.get("https://archive.org/metadata/cu31924067841738")

In [31]:
response = book.json()

In [32]:
response

{'alternate_locations': {'servers': [{'server': 'dn721705.ca.archive.org',
    'dir': '/0/items/cu31924067841738'}],
  'workable': [{'server': 'dn721705.ca.archive.org',
    'dir': '/0/items/cu31924067841738'}]},
 'created': 1760551499,
 'd1': 'ia601304.us.archive.org',
 'd2': 'ia801304.us.archive.org',
 'dir': '/12/items/cu31924067841738',
 'files': [{'name': '__ia_thumb.jpg',
   'source': 'original',
   'mtime': '1653667852',
   'size': '19027',
   'md5': '9e451931d5183c5fea9e1ff9710d3b30',
   'crc32': 'b91c4379',
   'sha1': '84f729b6118df1e60f1db3a75017b1312c7db959',
   'format': 'Item Tile',
   'rotation': '0'},
  {'name': 'cu31924067841738.djvu',
   'source': 'derivative',
   'format': 'DjVu',
   'original': 'cu31924067841738_djvu.xml',
   'md5': '244b045ec10de46d78e140f6c13a86e2',
   'mtime': '1257613982',
   'size': '5933724',
   'crc32': '38d9d914',
   'sha1': '8c915daa0ed20788d60424ea536db6d38b7e254c'},
  {'name': 'cu31924067841738.epub',
   'source': 'derivative',
   'original': 'cu31924067841738_abbyy.gz',
   'mtime': '1700038661',
   'size': '3639480',
   'md5': '9eecc6e95791ef536c548abfd0fca9f3',
   'crc32': '9e3a7aa1',
   'sha1': '94ecf7bf5d63d3b3456979413c73d768d80e714e',
   'format': 'EPUB'},
  {'name': 'cu31924067841738.gif',
   'source': 'derivative',
   'format': 'Animated GIF',
   'original': 'cu31924067841738_jp2.zip',
   'md5': 'c2f8ed4eb8a7bac1b4d5f366f77fc2b7',
   'mtime': '1257606177',
   'size': '181251',
   'crc32': '7cc44020',
   'sha1': '8a7cdc15c57012451d7258892b4591b895e14baa'},
  {'name': 'cu31924067841738.pdf',
   'source': 'derivative',
   'format': 'Text PDF',
   'original': 'cu31924067841738_djvu.xml',
   'md5': 'f505fad8976b81c43abb5b6799e7c83c',
   'mtime': '1257615102',
   'size': '8740882',
   'crc32': '5021e9da',
   'sha1': 'a0f45c625be0ea952888d8c3b4688d33a04de27a'},
  {'name': 'cu31924067841738_abbyy.gz',
   'source': 'derivative',
   'format': 'Abbyy GZ',
   'original': 'cu31924067841738_jp2.zip',
   'md5': '3efcf4ac745a9916c9fdadbaf3608e0d',
   'mtime': '1257612847',
   'size': '10051941',
   'crc32': 'fb9a6910',
   'sha1': 'ab69d06516b5fcdd8b4dd1d76744d80c3b906393'},
  {'name': 'cu31924067841738_archive.torrent',
   'source': 'metadata',
   'btih': 'dbb3a5e3d739ff981cce370ae3adc094293d9f35',
   'mtime': '1760334114',
   'size': '18255',
   'md5': '3ea0555cdbeaf147c9db53bdb997e386',
   'crc32': 'ee4d196e',
   'sha1': 'af73b09d53e1039f400f0b7584b02222a3e05cb8',
   'format': 'Archive BitTorrent'},
  {'name': 'cu31924067841738_cubook.zip',
   'source': 'original',
   'format': 'Raw Cornell Book Zip',
   'md5': '71a2a603a816a1781c4dd177f17a456c',
   'mtime': '1234288026',
   'size': '179443454',
   'crc32': '437d7f99',
   'sha1': '632d9de073f643893e5e2aae9daac9c7254a70a9',
   'filecount': '1585'},
  {'name': 'cu31924067841738_daisy.zip',
   'source': 'derivative',
   'original': 'cu31924067841738_abbyy.gz',
   'mtime': '1700815006',
   'size': '377129',
   'md5': 'e906c490136ffc2efffe0a4ff5cb9e2b',
   'crc32': '415094a9',
   'sha1': 'f66e26c1e07177b29e8aa5d175d8229ea00f0f63',
   'format': 'Daisy',
   'filecount': '9'},
  {'name': 'cu31924067841738_dc.xml',
   'source': 'original',
   'md5': '6ffc36703140a3f6e2f6db137c46fab3',
   'format': 'Dublin Core',
   'mtime': '1653667848',
   'size': '980',
   'crc32': '798f8d6d',
   'sha1': '0de4f659180e38e646e54eeefbfce9c549c7c3be'},
  {'name': 'cu31924067841738_djvu.txt',
   'source': 'derivative',
   'format': 'DjVuTXT',
   'original': 'cu31924067841738.djvu',
   'md5': 'e4acc7dd4c9412a22f25f6b4cc2520e4',
   'mtime': '1257615119',
   'size': '703987',
   'crc32': 'c1754981',
   'sha1': 'd69708e07a45f962cf9634f32eb508b126f725b0'},
  {'name': 'cu31924067841738_djvu.xml',
   'source': 'derivative',
   'format': 'Djvu XML',
   'original': 'cu31924067841738_abbyy.gz',
   'md5': '019af0104f33fdc7742fb1ef27857385',
   'mtime': '1257613185',
   'size': '6732478',
   'crc32': '5c2c3b7f',
   'sha1': '515b41707ef2fefe62b93e857b9fc60a31d1ad3d'},
  {'name': 'cu31924067841738_files.xml',
   'source': 'original',
   'format': 'Metadata',
   'md5': 'd4bcb853f8f1803dccebf0f526574eb9',
   'summation': 'md5'},
  {'name': 'cu31924067841738_jp2.zip',
   'source': 'derivative',
   'format': 'Single Page Processed JP2 ZIP',
   'original': 'cu31924067841738_cubook.zip',
   'md5': '52eba22e5c37b8eef49b1238cbfc9d06',
   'mtime': '1257606149',
   'size': '157442730',
   'crc32': 'ff3c0f90',
   'sha1': '3bf7141251c812b3cb8051cc479fbdb7574755b5',
   'filecount': '392'},
  {'name': 'cu31924067841738_marc.xml',
   'source': 'original',
   'md5': 'c1611e30638599ae7a8f73c023f99ef1',
   'format': 'MARC',
   'mtime': '1208421494',
   'size': '3208',
   'crc32': '8b02c48e',
   'sha1': 'ba6107c9a97775d48c60bc62c86ddc31d5d5d1eb'},
  {'name': 'cu31924067841738_meta.mrc',
   'source': 'original',
   'md5': '2518a47671c0125257b19f13948258c6',
   'format': 'MARC Binary',
   'mtime': '1208421492',
   'size': '875',
   'crc32': '88e2f9e9',
   'sha1': '9d17f959cd747c83671a84f9a981e3ebda0931d3'},
  {'name': 'cu31924067841738_meta.xml',
   'source': 'original',
   'format': 'Metadata',
   'mtime': '1752217834',
   'size': '2150',
   'md5': 'dcef8629a7457525e7da896054c5ef0d',
   'crc32': 'c62781ed',
   'sha1': 'c6d071e88ee61305bb222d0caf7e8a4f8b503698'},
  {'name': 'cu31924067841738_reviews.xml',
   'source': 'original',
   'mtime': '1760334111',
   'size': '1443',
   'md5': '732b04abade4df3cadd49954b08761da',
   'crc32': 'a603dcdc',
   'sha1': '43a8fc2a30a4c7d44ea81fa6f9320de5a5d43c62',
   'format': 'Metadata'},
  {'name': 'cu31924067841738_scandata.xml',
   'source': 'derivative',
   'format': 'Scandata',
   'original': 'cu31924067841738_djvu.xml',
   'md5': 'ffd644242913ee04f49345235b2435ff',
   'mtime': '1257613198',
   'size': '138830',
   'crc32': 'd3a77e14',
   'sha1': '22ff9f4a46443c82be468602c45d2accb9888079'}],
 'files_count': 19,
 'item_last_updated': 1760334114,
 'item_size': 373431824,
 'metadata': {'mediatype': 'texts',
  'collection': ['cornell', 'americana'],
  'title': 'The language of flowers; or flora symbolica. Including floral poetry, original and selected. With original illustrations, printed in colours by Terry',
  'identifier': 'cu31924067841738',
  'uploader': 'hank@archive.org',
  'addeddate': '2009-11-01 15:20:02',
  'identifier-access': 'http://www.archive.org/details/cu31924067841738',
  'identifier-ark': 'ark:/13960/t4vh63v8d',
  'sponsor': 'MSN',
  'contributor': 'Cornell University Library',
  'description': ['The metadata below describe the original scanning. Follow the "All Files: HTTP" link in the "View the book" box to the left to find XML files that contain more metadata about the original images and the derived formats (OCR results, PDF etc.). See also the <a href="http://www.archive.org/about/faqs.php#140" rel="ugc nofollow">What is the directory structure for the texts?</a> FAQ for information about file content and naming conventions.',
   'viii, 360 p. 20 cm'],
  'camera': 'EOS-1Ds MarkII',
  'lcamid': '338213',
  'rcamid': '336718',
  'operator': 'lbortle',
  'scanner': 'Kirtas APT 2400',
  'ppi': '300',
  'creator': 'Ingram, John Henry, 1842-1916',
  'publisher': 'London. New York. Frederick Warne and co.',
  'date': '1887',
  'subject': ['Plants', 'Flower language', 'Plants -- Folklore'],
  'language': 'eng',
  'imagecount': '392',
  'bookplateleaf': '0003',
  'ocr': 'ABBYY FineReader 8.0',
  'scandate': '20080417085647',
  'foldoutcount': '0',
  'repub_state': '4',
  'publicdate': '2009-11-07 17:32:07',
  'filesxml': 'Wed Mar 17 13:34:24 UTC 2010',
  'backup_location': 'ia903604_10',
  'openlibrary_edition': 'OL24187210M',
  'openlibrary_work': 'OL17078705W',
  'oclc-id': '63540312'},
 'reviews': [{'reviewbody': 'This is a black and white only scan. Too bad. ',
   'reviewtitle': 'No color illustrations here!',
   'reviewer': 'prose',
   'reviewdate': '2014-09-11 23:11:25',
   'createdate': '2014-09-11 23:11:25',
   'stars': '1'},
  {'reviewtitle': 'Good Quality',
   'reviewbody': "Beautiful book, but I think Terry forgot to bring his paints because it's all in black and white.",
   'stars': '4',
   'reviewer': 'Annalin503',
   'reviewdate': '2025-07-11 07:10:29',
   'createdate': '2025-07-11 07:10:29',
   'reviewer_itemname': '@annalin503'},
  {'reviewtitle': 'md2card',
   'reviewbody': 'This is a very good book with great content and is very surprising. I recommend it to everyone who is interested in similar topics.\n<a href="https://md2card.online" rel="ugc nofollow">md2card</a> : Turn your Markdown into beautiful cards.',
   'stars': '5',
   'reviewer': 'jsonchao',
   'reviewdate': '2025-10-13 05:41:48',
   'createdate': '2025-10-13 05:41:48',
   'reviewer_itemname': '@user513465'}],
 'server': 'ia801304.us.archive.org',
 'uniq': 1717187585,
 'workable_servers': ['ia801304.us.archive.org', 'ia601304.us.archive.org']}

In [34]:
response["dir"]

'/12/items/cu31924067841738'

In [35]:
response["metadata"]

{'mediatype': 'texts',
 'collection': ['cornell', 'americana'],
 'title': 'The language of flowers; or flora symbolica. Including floral poetry, original and selected. With original illustrations, printed in colours by Terry',
 'identifier': 'cu31924067841738',
 'uploader': 'hank@archive.org',
 'addeddate': '2009-11-01 15:20:02',
 'identifier-access': 'http://www.archive.org/details/cu31924067841738',
 'identifier-ark': 'ark:/13960/t4vh63v8d',
 'sponsor': 'MSN',
 'contributor': 'Cornell University Library',
 'description': ['The metadata below describe the original scanning. Follow the "All Files: HTTP" link in the "View the book" box to the left to find XML files that contain more metadata about the original images and the derived formats (OCR results, PDF etc.). See also the <a href="http://www.archive.org/about/faqs.php#140" rel="ugc nofollow">What is the directory structure for the texts?</a> FAQ for information about file content and naming conventions.',
  'viii, 360 p. 20 cm'],
 'camera': 'EOS-1Ds MarkII',
 'lcamid': '338213',
 'rcamid': '336718',
 'operator': 'lbortle',
 'scanner': 'Kirtas APT 2400',
 'ppi': '300',
 'creator': 'Ingram, John Henry, 1842-1916',
 'publisher': 'London. New York. Frederick Warne and co.',
 'date': '1887',
 'subject': ['Plants', 'Flower language', 'Plants -- Folklore'],
 'language': 'eng',
 'imagecount': '392',
 'bookplateleaf': '0003',
 'ocr': 'ABBYY FineReader 8.0',
 'scandate': '20080417085647',
 'foldoutcount': '0',
 'repub_state': '4',
 'publicdate': '2009-11-07 17:32:07',
 'filesxml': 'Wed Mar 17 13:34:24 UTC 2010',
 'backup_location': 'ia903604_10',
 'openlibrary_edition': 'OL24187210M',
 'openlibrary_work': 'OL17078705W',
 'oclc-id': '63540312'}

In [36]:
response['metadata']['title']

'The language of flowers; or flora symbolica. Including floral poetry, original and selected. With original illustrations, printed in colours by Terry'

In [37]:
response['reviews'][0]['reviewbody']

'This is a black and white only scan. Too bad. '

In [38]:
response['files'][6]['size']

'18255'

## Web Scraping

In [45]:
# Web Scraping 
response = requests.get('https://archive.org/details/cu31924067841738')

In [47]:
# Right click html file and then show preview to view web page
with open("flowers.html",mode='wb') as file:
    file.write(response.content)

In [ ]:
# Using headers 

url = "https://www.espn.com/college-football/rankings"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
                  " AppleWebKit/537.36 (KHTML, like Gecko)"
                  " Chrome/118.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://google.com"
}

response = requests.get(url, headers=headers)
print(response.status_code)

200

In [49]:
with open('APTop25.html',mode="wb") as file:
    file.write(response.content)

In [54]:
# random rotation of user-agent strings for scraping

import random,time 

user_agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64)...",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)...",
    "Mozilla/5.0 (X11; Linux x86_64)...",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "AppleWebKit/537.36 (KHTML, like Gecko)",
    "Chrome/118.0.0.0 Safari/537.36",
]

headers["User-Agent"] = random.choice(user_agents)
time.sleep(random.uniform(1, 3))

In [55]:
response = requests.get(url, headers=headers)
print(response.status_code)

200

### Beautiful Soup

In [56]:
from bs4 import BeautifulSoup

In [57]:
with open('APTop25.html') as ranks:
    soup = BeautifulSoup(ranks, "html.parser")

In [58]:
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<!-- ESPNFITT | be287f698242 | 13184537 | 6ca8849b | www.espn.com | Wed, 15 Oct 2025 19:24:35 GMT -->
<script src="https://dcf.espn.com/TWDC-DTCI/prod/Bootstrap.js"></script>
<script>
            (function(h,o,u,n,d) {
                h=h[d]=h[d]||{q:[],onReady:function(c){h.q.push(c)}}
                d=o.createElement(u);d.async=1;d.src=n
                n=o.getElementsByTagName(u)[0];n.parentNode.insertBefore(d,n)
            })(window,document,'script','https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum.js','DD_RUM');

            window.DD_RUM.onReady(function() {
                window.DD_RUM.setGlobalContext({
                    twdcgrid: {
                        yp_team_id: "67c86818ce5ff1871b58289f",
                        yp_service_id: "67b8d8e244357475ee4bd4b4",
                        datadog_log_index: "observability"
                    }
                });
            });
        </script>
<title data-react-helmet="true">2025 College Football Rankings - ESPN</title>
<meta content="Find the 2025 NCAAF rankings on ESPN, including the Coaches and AP poll for the top 25 NCAAF teams." data-react-helmet="true" name="description"/><meta content="116656161708917" data-react-helmet="true" property="fb:app_id"/><meta content="ESPN" data-react-helmet="true" property="og:site_name"/><meta content="https://www.espn.com/college-football/rankings" data-react-helmet="true" property="og:url"/><meta content="2025 College Football Rankings - ESPN" data-react-helmet="true" property="og:title"/><meta content="Find the 2025 NCAAF rankings on ESPN, including the Coaches and AP poll for the top 25 NCAAF teams." data-react-helmet="true" property="og:description"/><meta content="https://a.espncdn.com/combiner/i?img=/i/espn/misc_logos/500/ncaa_football.png" data-react-helmet="true" property="og:image"/><meta content="500" data-react-helmet="true" property="og:image:width"/><meta content="500" data-react-helmet="true" property="og:image:height"/><meta content="website" data-react-helmet="true" property="og:type"/><meta content="espn" data-react-helmet="true" name="twitter:site"/><meta content="https://www.espn.com/college-football/rankings" data-react-helmet="true" name="twitter:url"/><meta content="2025 College Football Rankings - ESPN" data-react-helmet="true" name="twitter:title"/><meta content="Find the 2025 NCAAF rankings on ESPN, including the Coaches and AP poll for the top 25 NCAAF teams." data-react-helmet="true" name="twitter:description"/><meta content="summary" data-react-helmet="true" name="twitter:card"/><meta content="https://a.espncdn.com/combiner/i?img=/i/espn/misc_logos/500/ncaa_football.png" data-react-helmet="true" name="twitter:image"/><meta content="ESPN" data-react-helmet="true" name="twitter:app:name:iphone"/><meta content="317469184" data-react-helmet="true" name="twitter:app:id:iphone"/><meta content="ESPN" data-react-helmet="true" name="twitter:app:name:googleplay"/><meta content="com.espn.score_center" data-react-helmet="true" name="twitter:app:id:googleplay"/><meta content="2025 College Football Rankings - ESPN" data-react-helmet="true" name="title"/><meta content="website" data-react-helmet="true" name="medium"/>
<meta content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
<meta content="IE=edge" http-equiv="x-ua-compatible"/>
<meta content="en_US" property="og:locale"/>
<link href="//cdn1.espn.net" rel="preconnect"/>
<link crossorigin="" href="https://tredir.espn.com" rel="preconnect"/>
<link crossorigin="" href="https://cdn.registerdisney.go.com" rel="preconnect"/>
<link crossorigin="" href="https://fan.api.espn.com" rel="preconnect"/>
<link crossorigin="" href="https://cdn.espn.com" rel="preconnect"/>
<link crossorigin="" href="https://a.espncdn.com" rel="preconnect"/>
<link crossorigin="" href="https://site.web.api.espn.com" rel="preconnect"/>
<link color="#990000" href="https://a.espncdn.com/prod/assets/icons/E.svg" rel="mask-icon" sizes="any"/>
<link href="https://a.espncdn.com/favicon.ico" rel="shortcut icon"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-57x57.png" rel="apple-touch-icon"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-57x57.png" rel="apple-touch-icon-precomposed"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114"/>
<link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-152x152.png" rel="apple-touch-icon-precomposed" sizes="152x152"/>
<link href="/manifest.json" rel="manifest"/>
<link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/fusion-e116a522.css" rel="stylesheet"><link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/1125-66c65781.css" rel="stylesheet"/><link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/espnfitt-0a7b592b.css" rel="stylesheet"/><link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/8227-39fd3c00.css" rel="stylesheet"/><link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/1992-328fafc3.css" rel="stylesheet"/><link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/rankings-facb14b0.css" rel="stylesheet"/><link data-react-helmet="true" href="https://www.espn.com/college-football/rankings" rel="canonical"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Publico/PublicoBannerExtraboldWeb.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansBlack.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSansCond/BentonSansCondBold.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_PlayoffProCond/PlayoffProCondBold.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_PlayoffProCond/PlayoffProCondBlack.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansBold.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansMedium.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansRegular.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteDisplay-CondensedHeavy-Web.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteText-Regular-Web.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteTextCondensed-Regular-Web.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteTextCondensed-Bold-Web.woff2" rel="preload" type="font/woff2"/><link data-react-helmet="true" href="https://www.espn.com/college-football/rankings" hreflang="en-us" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.br/futebol-americano/universitario/rankings" hreflang="pt-br" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.in/college-football/rankings" hreflang="en-in" rel="alternate"/><link data-react-helmet="true" href="https://africa.espn.com/college-football/rankings" hreflang="en-za" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.au/college-football/rankings" hreflang="en-au" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.ve/futbol-americano/colegial/rankings" hreflang="es-ve" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.cl/futbol-americano/colegial/rankings" hreflang="es-cl" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.mx/futbol-americano/colegial/rankings" hreflang="es-mx" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.co/futbol-americano/colegial/rankings" hreflang="es-co" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.pe/futbol-americano/colegial/rankings" hreflang="es-pe" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.ar/futbol-americano/colegial/rankings" hreflang="es-ar" rel="alternate"/><link data-react-helmet="true" href="https://espndeportes.espn.com/futbol-americano/colegial/rankings" hreflang="es-us" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.ph/college-football/rankings" hreflang="en-ph" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.co.uk/college-football/rankings" hreflang="en-gb" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.sg/college-football/rankings" hreflang="en-sg" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.gt/futbol-americano/colegial/rankings" hreflang="es-gt" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.uy/futbol-americano/colegial/rankings" hreflang="es-uy" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.do/futbol-americano/colegial/rankings" hreflang="es-do" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.ec/futbol-americano/colegial/rankings" hreflang="es-ec" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.com.pa/futbol-americano/colegial/rankings" hreflang="es-pa" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.co.cr/futbol-americano/colegial/rankings" hreflang="es-cr" rel="alternate"/><link data-react-helmet="true" href="https://www.espn.nl/college-football/rankings" hreflang="nl-nl" rel="alternate"/>
<script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/runtime-ad514337.js"></script><script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/dmp-sdk-ebb575f5.js"></script><script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/1125-f8923059.js"></script><script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/3242-7c023453.js"></script><script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/9264-abee4af7.js"></script><script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/4857-fae90ea1.js"></script><script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/8227-57bec612.js"></script><script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/8170-335490f0.js"></script><script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/6746-e2a20a3a.js"></script><script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/9637-a28734c4.js"></script>
<link as="script" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/_manifest.js" rel="prefetch"/><link as="script" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/espn-en-ed52e73d.js" rel="prefetch"/>
<link as="script" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/espnfitt-4b04e846.js" rel="prefetch"/>
<link as="script" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/rankings-1a34e75c.js" rel="prefetch"/>
<style id="fittLoadingStyle" type="text/css">
   .page-container,
   .Nav__Primary__Menu,
   .Nav__Secondary__Menu,
    .NavSecondary--GamePackage,
   .SoccerPerformers--gamepackage,
   .ScoreCell__Notes--footer,
   .Gamestrip,
   .Ad:before {
       opacity:                    0;
   }
</style>
<noscript>
<style type="text/css">
                div.HeaderScoreboardContainer, div.Ad, div.sponsored-content { display: none !important; }
                .page-container,
                .Nav__Primary .Nav__Primary__Menu .Nav__Primary__Menu__Item a,
                .Nav__Primary .Nav__Primary__Menu .Nav__Primary__Menu__Item .Nav__Primary__Menu__Link,
                .Nav__Secondary .Nav__Secondary__Menu .Nav__Secondary__Menu__Title .Nav__Secondary__Menu__Link,
                .Nav__Secondary .Nav__Secondary__Menu .Nav__Secondary__Menu__Item .Nav__Secondary__Menu__Link {
                    opacity: 1;
                }
            </style>
</noscript>
<script async="" src="https://a.espncdn.com/prod/scripts/analytics/ESPN_at_v2.rs.min.js"></script>
</link></head>
<body>
<img alt="" height="99999" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIHdpZHRoPSI5OTk5OXB4IiBoZWlnaHQ9Ijk5OTk5cHgiIHZpZXdCb3g9IjAgMCA5OTk5OSA5OTk5OSIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj48ZyBzdHJva2U9Im5vbmUiIGZpbGw9Im5vbmUiIGZpbGwtb3BhY2l0eT0iMCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9Ijk5OTk5IiBoZWlnaHQ9Ijk5OTk5Ij48L3JlY3Q+IDwvZz4gPC9zdmc+" style="pointer-events: none; position: absolute; top: 0; left: 0; width: 99%; height: 99%; max-width: 99%; max-height: 99%;" width="99999"/>

In [59]:
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <meta charset="utf-8"/>\n  <!-- ESPNFITT | be287f698242 | 13184537 | 6ca8849b | www.espn.com | Wed, 15 Oct 2025 19:24:35 GMT -->\n  <script src="https://dcf.espn.com/TWDC-DTCI/prod/Bootstrap.js">\n  </script>\n  <script>\n   (function(h,o,u,n,d) {\n                h=h[d]=h[d]||{q:[],onReady:function(c){h.q.push(c)}}\n                d=o.createElement(u);d.async=1;d.src=n\n                n=o.getElementsByTagName(u)[0];n.parentNode.insertBefore(d,n)\n            })(window,document,\'script\',\'https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum.js\',\'DD_RUM\');\n            \n            window.DD_RUM.onReady(function() {\n                window.DD_RUM.setGlobalContext({\n                    twdcgrid: {\n                        yp_team_id: "67c86818ce5ff1871b58289f",\n                        yp_service_id: "67b8d8e244357475ee4bd4b4",\n                        datadog_log_index: "observability"\n                    }\n                });\n            });\n  </script>\n  <title data-react-helmet="true">\n   2025 College Football Rankings - ESPN\n  </title>\n  <meta content="Find the 2025 NCAAF rankings on ESPN, including the Coaches and AP poll for the top 25 NCAAF teams." data-react-helmet="true" name="description"/>\n  <meta content="116656161708917" data-react-helmet="true" property="fb:app_id"/>\n  <meta content="ESPN" data-react-helmet="true" property="og:site_name"/>\n  <meta content="https://www.espn.com/college-football/rankings" data-react-helmet="true" property="og:url"/>\n  <meta content="2025 College Football Rankings - ESPN" data-react-helmet="true" property="og:title"/>\n  <meta content="Find the 2025 NCAAF rankings on ESPN, including the Coaches and AP poll for the top 25 NCAAF teams." data-react-helmet="true" property="og:description"/>\n  <meta content="https://a.espncdn.com/combiner/i?img=/i/espn/misc_logos/500/ncaa_football.png" data-react-helmet="true" property="og:image"/>\n  <meta content="500" data-react-helmet="true" property="og:image:width"/>\n  <meta content="500" data-react-helmet="true" property="og:image:height"/>\n  <meta content="website" data-react-helmet="true" property="og:type"/>\n  <meta content="espn" data-react-helmet="true" name="twitter:site"/>\n  <meta content="https://www.espn.com/college-football/rankings" data-react-helmet="true" name="twitter:url"/>\n  <meta content="2025 College Football Rankings - ESPN" data-react-helmet="true" name="twitter:title"/>\n  <meta content="Find the 2025 NCAAF rankings on ESPN, including the Coaches and AP poll for the top 25 NCAAF teams." data-react-helmet="true" name="twitter:description"/>\n  <meta content="summary" data-react-helmet="true" name="twitter:card"/>\n  <meta content="https://a.espncdn.com/combiner/i?img=/i/espn/misc_logos/500/ncaa_football.png" data-react-helmet="true" name="twitter:image"/>\n  <meta content="ESPN" data-react-helmet="true" name="twitter:app:name:iphone"/>\n  <meta content="317469184" data-react-helmet="true" name="twitter:app:id:iphone"/>\n  <meta content="ESPN" data-react-helmet="true" name="twitter:app:name:googleplay"/>\n  <meta content="com.espn.score_center" data-react-helmet="true" name="twitter:app:id:googleplay"/>\n  <meta content="2025 College Football Rankings - ESPN" data-react-helmet="true" name="title"/>\n  <meta content="website" data-react-helmet="true" name="medium"/>\n  <meta content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>\n  <meta content="IE=edge" http-equiv="x-ua-compatible"/>\n  <meta content="en_US" property="og:locale"/>\n  <link href="//cdn1.espn.net" rel="preconnect"/>\n  <link crossorigin="" href="https://tredir.espn.com" rel="preconnect"/>\n  <link crossorigin="" href="https://cdn.registerdisney.go.com" rel="preconnect"/>\n  <link crossorigin="" href="https://fan.api.espn.com" rel="preconnect"/>\n  <link crossorigin="" href="https://cdn.espn.com" rel="preconnect"/>\n  <link crossorigin="" href="https://a.espncdn.com" rel="preconnect"/>\n  <link crossorigin="" href="https://site.web.api.espn.com" rel="preconnect"/>\n  <link color="#990000" href="https://a.espncdn.com/prod/assets/icons/E.svg" rel="mask-icon" sizes="any"/>\n  <link href="https://a.espncdn.com/favicon.ico" rel="shortcut icon"/>\n  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-57x57.png" rel="apple-touch-icon"/>\n  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-57x57.png" rel="apple-touch-icon-precomposed"/>\n  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72"/>\n  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114"/>\n  <link href="https://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons-v2/espn-icon-152x152.png" rel="apple-touch-icon-precomposed" sizes="152x152"/>\n  <link href="/manifest.json" rel="manifest"/>\n  <link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/fusion-e116a522.css" rel="stylesheet">\n   <link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/1125-66c65781.css" rel="stylesheet"/>\n   <link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/espnfitt-0a7b592b.css" rel="stylesheet"/>\n   <link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/8227-39fd3c00.css" rel="stylesheet"/>\n   <link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/1992-328fafc3.css" rel="stylesheet"/>\n   <link data-react-helmet="true" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/css/rankings-facb14b0.css" rel="stylesheet"/>\n   <link data-react-helmet="true" href="https://www.espn.com/college-football/rankings" rel="canonical"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Publico/PublicoBannerExtraboldWeb.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansBlack.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSansCond/BentonSansCondBold.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_PlayoffProCond/PlayoffProCondBold.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_PlayoffProCond/PlayoffProCondBlack.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansBold.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansMedium.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_BentonSans/BentonSansRegular.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteDisplay-CondensedHeavy-Web.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteText-Regular-Web.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteTextCondensed-Regular-Web.woff2" rel="preload" type="font/woff2"/>\n   <link as="font" crossorigin="true" data-react-helmet="true" href="https://a.espncdn.com/fonts/_Ignite/ESPNIgniteTextCondensed-Bold-Web.woff2" rel="preload" type="font/woff2"/>\n   <link data-react-helmet="true" href="https://www.espn.com/college-football/rankings" hreflang="en-us" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.br/futebol-americano/universitario/rankings" hreflang="pt-br" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.in/college-football/rankings" hreflang="en-in" rel="alternate"/>\n   <link data-react-helmet="true" href="https://africa.espn.com/college-football/rankings" hreflang="en-za" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.au/college-football/rankings" hreflang="en-au" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.ve/futbol-americano/colegial/rankings" hreflang="es-ve" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.cl/futbol-americano/colegial/rankings" hreflang="es-cl" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.mx/futbol-americano/colegial/rankings" hreflang="es-mx" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.co/futbol-americano/colegial/rankings" hreflang="es-co" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.pe/futbol-americano/colegial/rankings" hreflang="es-pe" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.ar/futbol-americano/colegial/rankings" hreflang="es-ar" rel="alternate"/>\n   <link data-react-helmet="true" href="https://espndeportes.espn.com/futbol-americano/colegial/rankings" hreflang="es-us" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.ph/college-football/rankings" hreflang="en-ph" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.co.uk/college-football/rankings" hreflang="en-gb" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.sg/college-football/rankings" hreflang="en-sg" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.gt/futbol-americano/colegial/rankings" hreflang="es-gt" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.uy/futbol-americano/colegial/rankings" hreflang="es-uy" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.do/futbol-americano/colegial/rankings" hreflang="es-do" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.ec/futbol-americano/colegial/rankings" hreflang="es-ec" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.com.pa/futbol-americano/colegial/rankings" hreflang="es-pa" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.co.cr/futbol-americano/colegial/rankings" hreflang="es-cr" rel="alternate"/>\n   <link data-react-helmet="true" href="https://www.espn.nl/college-football/rankings" hreflang="nl-nl" rel="alternate"/>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/runtime-ad514337.js">\n   </script>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/dmp-sdk-ebb575f5.js">\n   </script>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/1125-f8923059.js">\n   </script>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/3242-7c023453.js">\n   </script>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/9264-abee4af7.js">\n   </script>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/4857-fae90ea1.js">\n   </script>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/8227-57bec612.js">\n   </script>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/8170-335490f0.js">\n   </script>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/6746-e2a20a3a.js">\n   </script>\n   <script defer="" src="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/9637-a28734c4.js">\n   </script>\n   <link as="script" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/_manifest.js" rel="prefetch"/>\n   <link as="script" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/espn-en-ed52e73d.js" rel="prefetch"/>\n   <link as="script" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/espnfitt-4b04e846.js" rel="prefetch"/>\n   <link as="script" href="//cdn1.espn.net/fitt/6ca8849b6e1e-release-10-14-2025.2.0.3370/client/espnfitt/rankings-1a34e75c.js" rel="prefetch"/>\n   <style id="fittLoadingStyle" type="text/css">\n    .page-container,\n   .Nav__Primary__Menu,\n   .Nav__Secondary__Menu,\n    .NavSecondary--GamePackage,\n   .SoccerPerformers--gamepackage,\n   .ScoreCell__Notes--footer,\n   .Gamestrip,\n   .Ad:before {\n       opacity:                    0;\n   }\n   </style>\n   <noscript>\n    <style type="text/css">\n     div.HeaderScoreboardContainer, div.Ad, div.sponsored-content { display: none !important; }\n                .page-container,\n                .Nav__Primary .Nav__Primary__Menu .Nav__Primary__Menu__Item a,\n                .Nav__Primary .Nav__Primary__Menu .Nav__Primary__Menu__Item .Nav__Primary__Menu__Link,\n                .Nav__Secondary .Nav__Secondary__Menu .Nav__Secondary__Menu__Title .Nav__Secondary__Menu__Link,\n                .Nav__Secondary .Nav__Secondary__Menu .Nav__Secondary__Menu__Item .Nav__Secondary__Menu__Link {\n                    opacity: 1;\n                }\n    </style>\n   </noscript>\n   <script async="" src="https://a.espncdn.com/prod/scripts/analytics/ESPN_at_v2.rs.min.js">\n   </script>\n  </link>\n </head>\n <body>\n  <img alt="" height="99999" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIHdpZHRoPSI5OTk5OXB4IiBoZWlnaHQ9Ijk5OTk5cHgiIHZpZXdCb3g9IjAgMCA5OTk5OSA5OTk5OSIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj48ZyBzdHJva2U9Im5vbmUiIGZpbGw9Im5vbmUiIGZpbGwtb3BhY2l0eT0iMCI+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9Ijk5OTk5IiBoZWlnaHQ9Ijk5OTk5Ij48L3JlY3Q+IDwvZz4gPC9zdmc+" style="pointer-events: none; position: absolute; top: 0; left: 0; width: 99%; height: 99%; max-width: 99%; max-height: 99%;" width="99999"/>\n  <div id="espnfitt">\n   <div id="DataWrapper">\n    <div id="fitt-analytics">\n     <div class="theme-light" id="themeProvider">\n      <div class="bp-mobileMDPlus bp-mobileLGPlus bp-tabletPlus bp-desktopPlus bp-desktopLGPlus" data-fitt-page-type="rankings">\n       <div id="lightboxContainer">\n       </div>\n       <div class="HeaderScoreboardWrapper">\n        <div class="HeaderScoreboardContainer HeaderScoreboardContainer--loading">\n         <section aria-label="HeaderScoreboard" class="HeaderScoreboard HeaderScoreboard--empty">\n          <button class="HiddenSkip" data-skip="content">\n           Skip to main content\n          </button>\n          <button class="HiddenSkip" data-skip="nav">\n           Skip to navigation\n          </button>\n          <div class="HeaderScoreboard__Wrapper">\n           <div class="HeaderScoreboard__Carousel">\n            <div class="HeaderScoreboard__Carousel__Nav HeaderScoreboard__Carousel__Nav--prev is-disabled">\n             <svg aria-hidden="true" class="icon__svg" viewbox="0 0 24 24">\n              <use xlink:href="#icon__caret__left">\n              </use>\n             </svg>\n            </div>\n            <div class="HeaderScoreboard__Carousel__Wrapper">\n             <div style="transform:translateX(0px);transition:0.7s ease">\n              <div class="HeaderScoreboard__Events">\n               <div class="HeaderScoreboard__SportSection">\n                <div class="ScoreCell ScoreCell--md ScoreCell--noLinks" role="group">\n                 <a class="ScoreCell__LinkOverlay">\n                 </a>\n                 <div class="ScoreCell__Link">\n                  <div class="ScoreCell__Link__Event__Detail">\n                   <div class="ScoreCell__CompetitorDetails">\n                    <ul class="ScoreCell__Competitors">\n                    </ul>\n                   </div>\n                  </div>\n                 </div>\n                </div>\n               </div>\n              </div>\n             </div>\n            </div>\n            <div class="HeaderScoreboard__Carousel__Nav HeaderScoreboard__Carousel__Nav--next is-disabled">\n             <svg aria-hidden="true" class="icon__svg" viewbox="0 0 24 24">\n              <use xlink:href="#icon__caret__right">\n              </use>\n             </svg>\n            </div>\n           </div>\n          </div>\n         </section>\n        </div>\n       </div>\n       <header class="db Site__Header__Wrapper sticky">\n        <div class="Site__Header db left-0 top-0 w-100 bg-clr-gray-02 Site__Header--espn">\n         <nav aria-label="Global Navigation" class="Nav__Primary center flex justify-between items-center">\n          <div class="Nav__Primary__Section Nav__Primary__Section--left">\n           <div class="Nav__Primary__Branding__Logo">\n            <div class="Nav__Primary__Branding__Wrapper">\n             <a aria-label="ESPN Home Page" class="AnchorLink Nav__Primary__Branding Nav__Primary__Branding--espn" data-track-nav_item="espn-logo" data-track-nav_layer="global nav" href="/" tabindex="0">\n              ESPN\n             </a>\n            </div>\n           </div>\n           <ul class="Nav__Primary__Menu flex Nav__Primary__Menu--left w-100">\n            <div>\n             <li class="Nav__Primary__Menu__Item flex items-center relative Nav__Primary__Menu__Item--espn-en n7 Nav__AccessibleMenuItem_Wrapper" data-testid="NavAccessibleMenuItem">\n              <a aria-label="ESPN NFL Home Page" aria-selected="false" class="AnchorLink Button--unstyled Nav__Primary__Menu__Link clr-white flex items-center" data-track-nav_item="nfl" data-track-nav_layer="global nav" href="/nfl/" id="nav-link-undefined" tabindex="0">\n               <div class="Nav__Primary__Menu__Item--button-container">\n                <span class="Nav__Text Nav__Primary__Menu__Item--text" data-resource-id="rankings.nfl_tab">\n                 NFL\n                </span>\n               </div>\n              </a>\n              <button aria-expanded="false" aria-haspopup="true" aria-label="NFL" class="Button--unstyled Nav__Primary__Menu__Toggle" tabindex="0">\n               <svg aria-hidden="true" class="Nav__SubmenuIndicatorIcon icon__svg fill-clr-white icon_svg--dark icon__svg" role="img" viewbox="0 0 24 24">\n                <title id="undefined-submenu">\n                 NFL\n                </title>\n                <use xlink:href="#icon__caret__down">\n                </use>\n               </svg>\n              </button>\n             </li>\n            </div>\n            <div>\n             <li class="Nav__Primary__Menu__Item flex items-center relative Nav__Primary__Menu__Item--espn-en n7 Nav__AccessibleMenuItem_Wrapper" data-testid="NavAccessibleMenuItem">\n              <a aria-label="ESPN NBA Home Page" aria-selected="false" class="AnchorLink Button--unstyled Nav__Primary__Menu__Link clr-white flex items-center" data-track-nav_item="nba" data-track-nav_layer="global nav" href="/nba/" id="nav-link-undefined" tabindex="0">\n               <div class="Nav__Primary__Menu__Item--button-container">\n                <span class="Nav__Text Nav__Primary__Menu__Item--text" data-resource-id="

In [68]:
title = soup.find_all("title")
title

[<title data-react-helmet="true">2025 College Football Rankings - ESPN</title>,
 <title id="undefined-submenu">NFL</title>,
 <title id="undefined-submenu">NBA</title>,
 <title id="undefined-submenu">MLB</title>,
 <title id="undefined-submenu">NCAAF</title>,
 <title id="undefined-submenu">WNBA</title>,
 <title id="undefined-submenu">NHL</title>,
 <title id="undefined-submenu">Soccer</title>,
 <title id="undefined-submenu">More Sports</title>,
 <title id="undefined-submenu">Watch</title>,
 <title id="undefined-submenu">ESPN BET</title>,
 <title id="undefined-submenu">Fantasy</title>,
 <title id="navSearchLabel">Search</title>,
 <title id="undefined-submenu">Rankings</title>,
 <title id="undefined-submenu">Stats</title>,
 <title id="undefined-submenu">Odds</title>,
 <title id="undefined-submenu">More</title>]

In [69]:
title[0].text.strip()

'2025 College Football Rankings - ESPN'

Scraping a Web Page

In [70]:
import requests
from bs4 import BeautifulSoup

In [71]:
item = "https://archive.org/details/cu31924011498676/mode/2up"

#Create an HTTP GET request
response = requests.get(item)

#Raise an exception if we made a request resulting in an error
response.raise_for_status()

#Access the content of the response in Unicode
content = response.text
#Print the result to check that it worked
print(content)

<!DOCTYPE html>
<html lang="en">
<!-- __ _ _ _ __| |_ (_)__ _____
    / _` | '_/ _| ' \| |\ V / -_)
    \__,_|_| \__|_||_|_| \_/\___| -->
  <head data-release=27223aa0 data-node="www29.us.archive.org">
    <title>Robinson Crusoe : Defoe, Daniel, 1661?-1731 : Free Download, Borrow, and Streaming : Internet Archive</title>

          <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <meta name="google-site-verification" content="Q2YSouphkkgHkFNP7FgAkc4TmBs1Gmag3uGNndb53B8" />
    <meta name="google-site-verification" content="bpjKvUvsX0lxfmjg19TLblckWkDpnptZEYsBntApxUk" />

    <meta name="baggage" content="sentry-trace_id=5e13ba4ab2394dcda436f51bde9529ee,sentry-sample_rate=0.001,sentry-transaction=%2Fdetails.php,sentry-public_key=94bf3037c1e245c8a927aaa4daad2dbb,sentry-environment=production,sentry-sampled=false"/>    <meta name="sentry-trace" content="5e13ba4ab2394dcda436f51bde9529ee-0bc6748debe94f30-0"/>
    <script  nonce="3735681c564e891db2a2263e3a58e4f9" >
/* @licstart  The following is the entire license notice for the
 * JavaScript code in this page.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @licend  The above is the entire license notice
 * for the JavaScript code in this page.
 */
</script>
        <meta charset="UTF-8">
                      <meta property="mediatype" content="texts">
                      <meta property="primary_collection" content="cornell">
            <script src="//archive.org/includes/build/js/ia-sentry.min.js?v=27223aa0" type="text/javascript"></script>
    <script src="//archive.org/includes/athena.js?v=27223aa0" type="text/javascript"></script>
    <script src="//archive.org/includes/apollo.js?v=27223aa0" type="text/javascript"></script>
    <script src="//archive.org/components/npm/lit/polyfill-support.js?v=27223aa0" type="text/javascript"></script>
    <script src="//archive.org/components/npm/@webcomponents/webcomponentsjs/webcomponents-bundle.js?v=27223aa0" type="text/javascript"></script>
<script nonce="3735681c564e891db2a2263e3a58e4f9" >
      window.__realDefine = customElements.define.bind(customElements);
      customElements.define = function() {
        try {
          return window.__realDefine.apply(this, arguments);
        } catch (e) {
          console.warn(e);
        }
      }
    </script>    <script src="//archive.org/includes/build/js/ia-topnav.min.js?v=27223aa0" type="text/javascript"></script>
    <script src="//archive.org/includes/build/js/details-bookreader.min.js?v=27223aa0" type="text/javascript"></script>
    <link href="/includes/build/BookReader/BookReader.css?v=27223aa0" rel="stylesheet" type="text/css"/>
    <link href="/bookreader/BookReader-ia.css?v=27223aa0" rel="stylesheet" type="text/css"/>
<meta name="AB:BrExperimentsPanel" content="On"><meta name="description" content="The metadata below describe the original scanning. Follow the All Files: HTTP link in the View the book box to the left to find XML files that contain more..."/>
                      <meta property="og:title" content="Robinson Crusoe : Defoe, Daniel, 1661?-1731 : Free Download, Borrow, and Streaming : Internet Archive">
                      <meta property="og:description" content="The metadata below describe the original scanning. Follow the All Files: HTTP link in the View the book box to the left to find XML files that contain more...">
                      <meta property="og:site_name" content="Internet Archive">
                      <meta property="og:image" content="https://archive.org/services/img/cu31924011498676">
                      <meta property="og:url" content="https://archive.org/details/cu31924011498676">
        <meta property="twitter:card" content="player"/>
<meta property="twitter:site" content="@internetarchive"/>
<meta property="twitter:account_id" content="18957805"/>
<meta property="twitter:description" content="The metadata below describe the original scanning. Follow the All Files: HTTP link in the View the book box to the left to find XML files that contain more..."/>
<meta property="twitter:title" content="Robinson Crusoe : Defoe, Daniel, 1661?-1731 : Free Download, Borrow, and Streaming : Internet Archive"/>
<meta property="twitter:image" content="https://archive.org/services/img/cu31924011498676/full/pct:200/0/default.jpg"/>
<link rel="canonical" href="https://archive.org/details/cu31924011498676">
    <script type="application/ld+json">
      {"@context":"http:\/\/schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https:\/\/archive.org\/details\/texts","name":"Texts","image":"https:\/\/archive.org\/services\/img\/texts"}}]}    </script>
    <meta name="monetization" content="$ilp.uphold.com/D7BwPKMQzBiD">
    <link href="//archive.org/includes/build/css/archive.min.css?v=27223aa0" rel="stylesheet" type="text/css"/>
    <link rel="SHORTCUT ICON" href="https://archive.org/images/glogo.jpg"/>
  </head>
  <body class="navia ia-module tiles responsive">
    <a href="#maincontent" class="hidden-for-screen-readers">Skip to main content</a>

    <!-- Wraps all page content -->
    <div id="wrap"
              itemscope
        itemtype="http://schema.org/Book"
          >
                    <div class="ia-banners">
              <div
        class="ia-banner hidden post-appeal-20240905"
        data-campaign="post-appeal-20240905">
        <p><a href="https://change.org/LetReadersRead" rel="ugc nofollow">Ask the publishers</a> to restore access to 500,000+ books.</p>
        <form class="banner-close" action="" method="get" data-action="ia-banner-close">
          <fieldset>
            <button aria-label="Close Banner" type="submit"></button>
          </fieldset>
        </form>
      </div>
          </div>
                <link href="//archive.org/components/donation-banner/banner.css?v=27223aa0" rel="stylesheet" type="text/css"/>
    <link href="//archive.org/components/donation-banner/banner-template-styles/chevron.css?v=27223aa0" rel="stylesheet" type="text/css"/>
      <header
      id="donate_banner"
      class="js-donate-banner formdesign-psa"
      itemscope
      itemtype="http://schema.org/WPAdBlock"
      data-donationSourceData="ctx=ia;uid=7aa7a25910a1ac81fd66609ad5f735b3;url=https%3A%2F%2Farchive.org%3A443%2Fdetails.php%3Fidentifier%3Dcu31924011498676%26%2Fmode%2F2up"
      data-exp="20251008OctGFMdeploy"
      data-variant="IAOctPSAdeployGFM"
      data-platform="ia"
      data-baseUrl="https://archive.org"
      data-platform="ia"
      data-bannerTemplate="psa"
      data-bannerBackground="default"
      data-snowfall="off"
      data-selectedTextColor="#000000"
      data-selectedFillColor="#F9BF3B"
      data-paymentOptionFillColor=""
      data-paymentOptionTextColor=""
      data-formBgColor="#ffffff"
      data-formTextColor="#000000"
      data-donatePageSelectedTextColor="#000000"
      data-donatePageSelectedFillColor="#F9BF3B"
      data-psaBannerDestinationUrl=""
      data-variantDollarAmounts='[10, 15, 50]'                  data-debugMode="false"
      style="--donationBannerChevronBG: #F9BF3B;"
      >
                  <div class="ia-banner visible psa">
            <div class="appeal-text" style="--donationBannerAppealTextColor: #000000;">
              <div class="desktop-body-content"><b>Can You Chip In? </b>We’re celebrating our 1 trillionth archived web page. If you find our library useful, learn how you can <b><a href="https://donate.archive.org/campaign/1-trillion-webpages-p2p/c731122">help us fundraise!</a></b></div>
              <div class="mobile-body-content"><b>Can You Chip In? </b>We’re celebrating our 1 trillionth archived web page. If you find our library useful, learn how you can <b><a href="https://donate.archive.org/campaign/1-trillion-webpages-p2p/c731122">help us fundraise!</a></b></div>
            </div>
            <form id="donate-close-button" class="banner-close" aria-label="Close banner">
              <span class="sr-only">Close banner</span>
              <fieldset>
                <button aria-label="Close Banner" type="submit"></button>
              </fieldset>
            </form>
            <div style="display: none;">      <div class="donation-form-container">
        <donation-form-edit-donation
          amountOptions='[10, 15, 50]'          defaultSelectedAmount='15'          amountTitleDisplayMode="slot"
          customAmountMode="hide"
          customFeesCheckboxMode="hide"
          frequencySelectionMode="hide"
          stepNumberMode="hidenumbers"
          class="minimal-widget focus-on-child-only"
          style="--paymentButtonSelectedFontColor: #000000;--paymentButtonSelectedColor: #F9BF3B;--formSectionTextColor: #000000;"
        >
          <div slot="edit-donation-amount-title">
            <p style="font-size: 1.8rem; line-height: calc(1.2rem * 2); margin: 0;"><b>Can You Chip In?</b> (USD)</p>
          </div>
        </donation-form-edit-donation>
      </div>
    </div>
          </div>
              </header>
              <div id="topnav">
              <input class="js_nav_tweaks" type="hidden" value='[]'/>
    <!-- Shady DOM styles for icon-hamburger -->
<style scope="icon-hamburger-1">
  .icon-hamburger-1 svg.icon-hamburger {
    display: block;
    height: 4rem;
    width: 4rem;
  }

  .icon-hamburger-1 .fill-color.icon-hamburger {
    fill: #fff;
  }
</style><!-- Shady DOM styles for login-button -->
<style scope="login-button-1">
  .login-button-1 .dropdown-toggle.login-button {
    display: block;
    text-transform: uppercase;
    color: #ccc;
    cursor: pointer;
  }

  .login-button-1 .dropdown-toggle.login-button svg.login-button {
    height: 100%;
    width: 4rem;
  }

  .login-button-1 .dropdown-toggle.login-button .fill-color.login-button {
    fill: #999;
  }

  .login-button-1 .dropdown-toggle.login-button:active .fill-color.login-button,
  .login-button-1 .dropdown-toggle.login-button:focus .fill-color.login-button,
  .login-button-1 .dropdown-toggle.login-button:hover .fill-color.login-button {
    fill: #fff;
  }

  .login-button-1 .active.login-button {
    border-radius: 1rem 1rem 0 0;
    background: #333;
  }

  .login-button-1 .active.login-button .fill-color.login-button {
    fill: #fff;
  }

  .login-button-1 span.login-button {
    display: none;
    font-size: 1.4rem;
    text-transform: uppercase;
    color: #999;
  }

  .login-button-1 span.login-button a.login-button {
    color: inherit;
    text-decoration: none;
    outline: 0;
  }

  .login-button-1 a.login-button:hover,
  .login-button-1 a.login-button:active,
  .login-button-1 a.login-button:focus {
    color: #fff !important;
    outline: none !important;
    outline-offset: inherit !important;
  }

  @media (min-width: 890px) {
    .login-button-1 .logged-out-toolbar.login-button {
      padding: 1rem 0.5rem;
      vertical-align: middle;
    }

    .login-button-1 .active.login-button {
      background: transparent;
    }

    .login-button-1 .dropdown-toggle.login-button {
      display: inline-block;
      vertical-align: middle;
    }

    .login-button-1 .dropdown-toggle.login-button svg.login-button {
      height: 3rem;
      width: 3rem;
      display: block;
    }

    .login-button-1 span.login-button {
      display: inline;
      vertical-align: middle;
    }

  }
</style><!-- Shady DOM styles for nav-search -->
<style scope="nav-search-1">
  .nav-search-1 input.nav-search[type="text"] {
    color: #222;
  }

  .nav-search-1 input.nav-search:focus {
    outline: none;
  }

  .nav-search-1 button.nav-search {
    background: none;
    color: inherit;
    border: none;
    font: inherit;
    cursor: pointer;
  }

  .nav-search-1 button.nav-search:focus {
    outline: none;
  }

  .nav-search-1 .search.nav-search {
    padding-top: 0;
    margin-right: 0.5rem;
  }

  .nav-search-1 .search.nav-search svg.nav-search {
    position: relative;
    fill: ;
  }

  .nav-search-1 .search-activated.nav-search {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    position: absolute;
    top: 0;
    right: 4rem;
    bottom: 0;
    left: 4rem;
    z-index: 3;
    padding: 0.5rem 0.2rem;
    border-radius: 1rem 1rem 0 0;
    background: #333;
  }

  .nav-search-1 .search-inactive.nav-search {
    display: none;
  }

  .nav-search-1 .search-activated.nav-search .highlight.nav-search,
  .nav-search-1 .search-activated.nav-search .search.nav-search {
    background: #fff;
    border-radius: 0.5rem;
  }

  .nav-search-1 .search-activated.nav-search .highlight.nav-search {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    width: 100%;
    margin: 0 0.5rem;
  }

  .nav-search-1 .search-activated.nav-search .search.nav-search {
    height: 100%;
    padding: 0;
    margin-right: 0;
    -ms-flex-item-align: center;
    -ms-grid-row-align: center;
    align-self: center;
  }

  .nav-search-1 .search-activated.nav-search .search.nav-search svg.nav-search {
    height: 3rem;
    width: 3rem;
  }

  .nav-search-1 .search-activated.nav-search .search-field.nav-search {
    width: 100%;
    height: 100%;
    box-sizing: border-box;
    padding-left: 1rem;
    border-radius: 0.5rem;
    border: none;
    font-size: 1.6rem;
    text-align: center;
  }

  .nav-search-1 .search-activated.nav-search .search-field.nav-search:focus {
    outline: none;
  }

  @keyframes fade-in-nav-search-1 {
    0% {
      opacity: 0;
    }

    100% {
      opacity: 1;
    }

  }

  .nav-search-1 .fade-in.nav-search {
    animation: fade-in-nav-search-1 0.2s forwards;
  }

  @media (min-width: 890px) {
    .nav-search-1 .search.nav-search svg.nav-search {
      display: inline;
      width: 2.8rem;
      height: 2.8rem;
      vertical-align: -14px;
    }

    .nav-search-1 .search.nav-search path.nav-search {
      fill: #333;
    }

    .nav-search-1 .search-inactive.nav-search,
    .nav-search-1 .search-activated.nav-search {
      display: block;
      position: static;
      padding: 1.1rem 0.2rem;
      background: transparent;
    }

    .nav-search-1 .search-activated.nav-search .highlight.nav-search {
      width: 13rem;
      height: 2.8rem;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: reverse;
      -ms-flex-direction: row-reverse;
      flex-direction: row-reverse;
    }

    .nav-search-1 .search-activated.nav-search .search-field.nav-search {
      width: calc(100% - 28px);
      height: 100%;
      padding-left: 0;
      font-size: 1.4rem;
      text-align: left;
    }

    .nav-search-1 .search-activated.nav-search .search.nav-search svg.nav-search {
      width: 2.8rem;
      height: 2.8rem;
    }

  }
</style><!-- Shady DOM styles for media-button -->
<style scope="media-button-1">
  .media-button-1 a.media-button {
    display: inline-block;
    text-decoration: none;
  }

  .media-button-1 .menu-item.media-button {
    display: inline-block;
    width: 100%;
    padding: 0;
    font-size: 1.6rem;
    text-align: left;
    background: transparent;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
  }

  .media-button-1 .menu-item.media-button:focus {
    outline: none;
  }

  .media-button-1 .label.media-button {
    display: inline-block;
    padding: 0;
    font-weight: 400;
    color: #fff;
    text-align: left;
    vertical-align: middle;
  }

  .media-button-1 .menu-item.media-button>.icon.media-button {
    display: inline-flex;
    vertical-align: middle;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
  }

  .media-button-1 .menu-item.media-button>.icon.media-button>svg.media-button {
    height: 4rem;
    width: 4rem;
  }

  .media-button-1 .menu-item.selected.media-button .icon.media-button {
    background-color: #333;
    border-radius: 1rem 0 0 1rem;
  }

  .media-button-1 .icon.media-button .fill-color.media-button {
    fill: #999;
  }

  .media-button-1 .icon.active.media-button .fill-color.media-button {
    fill: #fff;
  }

  .media-button-1 .donate.media-button .fill-color.media-button {
    fill: #f00;
  }

  @media (min-width: 890px) {
    .media-button-1 .menu-item.media-button {
      width: auto;
      height: 5rem;
      color: #999;
      display: inline-flex;
    }

    .media-button-1 .menu-item.media-button:hover,
    .media-button-1 .menu-item.media-button:active,
    .media-button-1 .menu-item.media-button:focus {
      color: #fff;
    }

    .media-button-1 .menu-item.media-button:hover .fill-color.media-button,
    .media-button-1 .menu-item.media-button:active .fill-color.media-button,
    .media-button-1 .menu-item.media-button:focus .fill-color.media-button {
      fill: #fff;
    }

    .media-button-1 .label.media-button {
      display: none;
    }

    .media-button-1 .label.media-button,
    .media-button-1 .web.media-button:after {
      padding-right: 1rem;
      font-size: 1.3rem;
      text-transform: uppercase;
      color: inherit;
    }

    .media-button-1 .web.media-button:after {
      display: none;
      content: "web";
    }

    .media-button-1 .donate.media-button,
    .media-button-1 .more.media-button {
      display: none;
    }

    .media-button-1 .menu-item.selected.media-button {
      background: #474747;
    }

    .media-button-1 .menu-item.selected.media-button .label.media-button,
    .media-button-1 .menu-item.selected.web.media-button:after {
      color: #fff;
    }

    .media-button-1 .menu-item.selected.media-button .icon.media-button {
      background: transparent;
    }

    .media-button-1 .web.selected.media-button .fill-color.media-button {
      fill: #ffcd27;
    }

    .media-button-1 .texts.selected.media-button .fill-color.media-button {
      fill: #faab3c;
    }

    .media-button-1 .video.selected.media-button .fill-color.media-button {
      fill: #f1644b;
    }

    .media-button-1 .audio.selected.media-button .fill-color.media-button {
      fill: #00adef;
    }

    .media-button-1 .software.selected.media-button .fill-color.media-button {
      fill: #9ecc4f;
    }

    .media-button-1 .images.selected.media-button .fill-color.media-button {
      fill: #aa99c9;
    }

  }

  @media (min-width: 1200px) {

    .media-button-1 .label.media-button,
    .media-button-1 .web.media-button:after {
      display: inline;
    }

    .media-button-1 .web.media-button .label.media-button {
      display: none;
    }

  }
</style><!-- Shady DOM styles for media-menu -->
<style scope="media-menu-1">
  .media-menu-1 {
    outline: none;
  }

  .media-menu-1 .media-menu-inner.media-menu {
    z-index: -1;
    top: -40rem;
    background-color: #222;
    margin: 0;
    overflow: hidden;
    transition-duration: 0.2s;
    transition-property: top;
    transition-timing-function: ease;
  }

  .media-menu-1 .menu-group.media-menu {
    position: relative;
    line-height: normal;
  }

  @media (max-width: 889px) {
    .media-menu-1 .media-menu-inner.media-menu {
      position: absolute;
      width: 100%;
    }

    .media-menu-1 .open.media-menu .media-menu-inner.media-menu {
      top: 0;
    }

    .media-menu-1 .overflow-clip.media-menu {
      position: absolute;
      z-index: -1;
      top: 4rem;
      left: 0;
      height: 0;
      width: 100%;
      overflow: hidden;

In [72]:
# Parsing
soup = BeautifulSoup(response.text, 'html.parser')

In [73]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <!-- __ _ _ _ __| |_ (_)__ _____
    / _` | '_/ _| ' \| |\ V / -_)
    \__,_|_| \__|_||_|_| \_/\___| -->
 <head data-node="www29.us.archive.org" data-release="27223aa0">
  <title>
   Robinson Crusoe : Defoe, Daniel, 1661?-1731 : Free Download, Borrow, and Streaming : Internet Archive
  </title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Q2YSouphkkgHkFNP7FgAkc4TmBs1Gmag3uGNndb53B8" name="google-site-verification"/>
  <meta content="bpjKvUvsX0lxfmjg19TLblckWkDpnptZEYsBntApxUk" name="google-site-verification"/>
  <meta content="sentry-trace_id=5e13ba4ab2394dcda436f51bde9529ee,sentry-sample_rate=0.001,sentry-transaction=%2Fdetails.php,sentry-public_key=94bf3037c1e245c8a927aaa4daad2dbb,sentry-environment=production,sentry-sampled=false" name="baggage"/>
  <meta content="5e13ba4ab2394dcda436f51bde9529ee-0bc6748debe94f30-0" name="sentry-trace"/>
  <script nonce="3735681c564e891db2a2263e3a58e4f9">
   /* @licstart  The following is the entire license notice for the
 * JavaScript code in this page.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @licend  The above is the entire license notice
 * for the JavaScript code in this page.
 */
  </script>
  <meta charset="utf-8"/>
  <meta content="texts" property="mediatype"/>
  <meta content="cornell" property="primary_collection"/>
  <script src="//archive.org/includes/build/js/ia-sentry.min.js?v=27223aa0" type="text/javascript">
  </script>
  <script src="//archive.org/includes/athena.js?v=27223aa0" type="text/javascript">
  </script>
  <script src="//archive.org/includes/apollo.js?v=27223aa0" type="text/javascript">
  </script>
  <script src="//archive.org/components/npm/lit/polyfill-support.js?v=27223aa0" type="text/javascript">
  </script>
  <script src="//archive.org/components/npm/@webcomponents/webcomponentsjs/webcomponents-bundle.js?v=27223aa0" type="text/javascript">
  </script>
  <script nonce="3735681c564e891db2a2263e3a58e4f9">
   window.__realDefine = customElements.define.bind(customElements);
      customElements.define = function() {
        try {
          return window.__realDefine.apply(this, arguments);
        } catch (e) {
          console.warn(e);
        }
      }
  </script>
  <script src="//archive.org/includes/build/js/ia-topnav.min.js?v=27223aa0" type="text/javascript">
  </script>
  <script src="//archive.org/includes/build/js/details-bookreader.min.js?v=27223aa0" type="text/javascript">
  </script>
  <link href="/includes/build/BookReader/BookReader.css?v=27223aa0" rel="stylesheet" type="text/css"/>
  <link href="/bookreader/BookReader-ia.css?v=27223aa0" rel="stylesheet" type="text/css"/>
  <meta content="On" name="AB:BrExperimentsPanel"/>
  <meta content="The metadata below describe the original scanning. Follow the All Files: HTTP link in the View the book box to the left to find XML files that contain more..." name="description">
   <meta content="Robinson Crusoe : Defoe, Daniel, 1661?-1731 : Free Download, Borrow, and Streaming : Internet Archive" property="og:title"/>
   <meta content="The metadata below describe the original scanning. Follow the All Files: HTTP link in the View the book box to the left to find XML files that contain more..." property="og:description"/>
   <meta content="Internet Archive" property="og:site_name"/>
   <meta content="https://archive.org/services/img/cu31924011498676" property="og:image"/>
   <meta content="https://archive.org/details/cu31924011498676" property="og:url"/>
   <meta content="player" property="twitter:card">
    <meta content="@internetarchive" property="twitter:site">
     <meta content="18957805" property="twitter:account_id">
      <meta content="The metadata below describe the original scanning. Follow the All Files: HTTP link in the View the book box to the left to find XML files that contain more..." property="twitter:description">
       <meta content="Robinson Crusoe : Defoe, Daniel, 1661?-1731 : Free Download, Borrow, and Streaming : Internet Archive" property="twitter:title">
        <meta content="https://archive.org/services/img/cu31924011498676/full/pct:200/0/default.jpg" property="twitter:image">
         <link href="https://archive.org/details/cu31924011498676" rel="canonical"/>
         <script type="application/ld+json">
          {"@context":"http:\/\/schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https:\/\/archive.org\/details\/texts","name":"Texts","image":"https:\/\/archive.org\/services\/img\/texts"}}]}
         </script>
         <meta content="$ilp.uphold.com/D7BwPKMQzBiD" name="monetization"/>
         <link href="//archive.org/includes/build/css/archive.min.css?v=27223aa0" rel="stylesheet" type="text/css">
          <link href="https://archive.org/images/glogo.jpg" rel="SHORTCUT ICON"/>
         </link>
        </meta>
       </meta>
      </meta>
     </meta>
    </meta>
   </meta>
  </meta>
 </head>
 <body class="navia ia-module tiles responsive">
  <a class="hidden-for-screen-readers" href="#maincontent">
   Skip to main content
  </a>
  <!-- Wraps all page content -->
  <div id="wrap" itemscope="" itemtype="http://schema.org/Book">
   <div class="ia-banners">
    <div class="ia-banner hidden post-appeal-20240905" data-campaign="post-appeal-20240905">
     <p>
      <a href="https://change.org/LetReadersRead" rel="ugc nofollow">
       Ask the publishers
      </a>
      to restore access to 500,000+ books.
     </p>
     <form action="" class="banner-close" data-action="ia-banner-close" method="get">
      <fieldset>
       <button aria-label="Close Banner" type="submit">
       </button>
      </fieldset>
     </form>
    </div>
   </div>
   <link href="//archive.org/components/donation-banner/banner.css?v=27223aa0" rel="stylesheet" type="text/css"/>
   <link href="//archive.org/components/donation-banner/banner-template-styles/chevron.css?v=27223aa0" rel="stylesheet" type="text/css"/>
   <header class="js-donate-banner formdesign-psa" data-bannerbackground="default" data-bannertemplate="psa" data-baseurl="https://archive.org" data-debugmode="false" data-donatepageselectedfillcolor="#F9BF3B" data-donatepageselectedtextcolor="#000000" data-donationsourcedata="ctx=ia;uid=7aa7a25910a1ac81fd66609ad5f735b3;url=https%3A%2F%2Farchive.org%3A443%2Fdetails.php%3Fidentifier%3Dcu31924011498676%26%2Fmode%2F2up" data-exp="20251008OctGFMdeploy" data-formbgcolor="#ffffff" data-formtextcolor="#000000" data-paymentoptionfillcolor="" data-paymentoptiontextcolor="" data-platform="ia" data-psabannerdestinationurl="" data-selectedfillcolor="#F9BF3B" data-selectedtextcolor="#000000" data-snowfall="off" data-variant="IAOctPSAdeployGFM" data-variantdollaramounts="[10, 15, 50]" id="donate_banner" itemscope="" itemtype="http://schema.org/WPAdBlock" style="--donationBannerChevronBG: #F9BF3B;">
    <div class="ia-banner visible psa">
     <div class="appeal-text" style="--donationBannerAppealTextColor: #000000;">
      <div class="desktop-body-content">
       <b>
        Can You Chip In?
       </b>
       We’re celebrating our 1 trillionth archived web page. If you find our library useful, learn how you can
       <b>
        <a href="https://donate.archive.org/campaign/1-trillion-webpages-p2p/c731122">
         help us fundraise!
        </a>
       </b>
      </div>
      <div class="mobile-body-content">
       <b>
        Can You Chip In?
       </b>
       We’re celebrating our 1 trillionth archived web page. If you find our library useful, learn how you can
       <b>
        <a href="https://donate.archive.org/campaign/1-trillion-webpages-p2p/c731122">
         help us fundraise!
        </a>
       </b>
      </div>
     </div>
     <form aria-label="Close banner" class="banner-close" id="donate-close-button">
      <span class="sr-only">
       Close banner
      </span>
      <fieldset>
       <button aria-label="Close Banner" type="submit">
       </button>
      </fieldset>
     </form>
     <div style="display: none;">
      <div class="donation-form-container">
       <donation-form-edit-donation amountoptions="[10, 15, 50]" amounttitledisplaymode="slot" class="minimal-widget focus-on-child-only" customamountmode="hide" customfeescheckboxmode="hide" defaultselectedamount="15" frequencyselectionmode="hide" stepnumbermode="hidenumbers" style="--paymentButtonSelectedFontColor: #000000;--paymentButtonSelectedColor: #F9BF3B;--formSectionTextColor: #000000;">
        <div slot="edit-donation-amount-title">
         <p style="font-size: 1.8rem; line-height: calc(1.2rem * 2); margin: 0;">
          <b>
           Can You Chip In?
          </b>
          (USD)
         </p>
        </div>
       </donation-form-edit-donation>
      </div>
     </div>
    </div>
   </header>
   <div id="topnav">
    <input class="js_nav_tweaks" type="hidden" value="[]"/>
    <!-- Shady DOM styles for icon-hamburger -->
    <style scope="icon-hamburger-1">
     .icon-hamburger-1 svg.icon-hamburger {
    display: block;
    height: 4rem;
    width: 4rem;
  }

  .icon-hamburger-1 .fill-color.icon-hamburger {
    fill: #fff;
  }
    </style>
    <!-- Shady DOM styles for login-button -->
    <style scope="login-button-1">
     .login-button-1 .dropdown-toggle.login-button {
    display: block;
    text-transform: uppercase;
    color: #ccc;
    cursor: pointer;
  }

  .login-button-1 .dropdown-toggle.login-button svg.login-button {
    height: 100%;
    width: 4rem;
  }

  .login-button-1 .dropdown-toggle.login-button .fill-color.login-button {
    fill: #999;
  }

  .login-button-1 .dropdown-toggle.login-button:active .fill-color.login-button,
  .login-button-1 .dropdown-toggle.login-button:focus .fill-color.login-button,
  .login-button-1 .dropdown-toggle.login-button:hover .fill-color.login-button {
    fill: #fff;
  }

  .login-button-1 .active.login-button {
    border-radius: 1rem 1rem 0 0;
    background: #333;
  }

  .login-button-1 .active.login-button .fill-color.login-button {
    fill: #fff;
  }

  .login-button-1 span.login-button {
    display: none;
    font-size: 1.4rem;
    text-transform: uppercase;
    color: #999;
  }

  .login-button-1 span.login-button a.login-button {
    color: inherit;
    text-decoration: none;
    outline: 0;
  }

  .login-button-1 a.login-button:hover,
  .login-button-1 a.login-button:active,
  .login-button-1 a.login-button:focus {
    color: #fff !important;
    outline: none !important;
    outline-offset: inherit !important;
  }

  @media (min-width: 890px) {
    .login-button-1 .logged-out-toolbar.login-button {
      padding: 1rem 0.5rem;
      vertical-align: middle;
    }

    .login-button-1 .active.login-button {
      background: transparent;
    }

    .login-button-1 .dropdown-toggle.login-button {
      display: inline-block;
      vertical-align: middle;
    }

    .login-button-1 .dropdown-toggle.login-button svg.login-button {
      height: 3rem;
      width: 3rem;
      display: block;
    }

    .login-button-1 span.login-button {
      display: inline;
      vertical-align: middle;
    }

  }
    </style>
    <!-- Shady DOM styles for nav-search -->
    <style scope="nav-search-1">
     .nav-search-1 input.nav-search[type="text"] {
    color: #222;
  }

  .nav-search-1 input.nav-search:focus {
    outline: none;
  }

  .nav-search-1 button.nav-search {
    background: none;
    color: inherit;
    border: none;
    font: inherit;
    cursor: pointer;
  }

  .nav-search-1 button.nav-search:focus {
    outline: none;
  }

  .nav-search-1 .search.nav-search {
    padding-top: 0;
    margin-right: 0.5rem;
  }

  .nav-search-1 .search.nav-search svg.nav-search {
    position: relative;
    fill: ;
  }

  .nav-search-1 .search-activated.nav-search {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    position: absolute;
    top: 0;
    right: 4rem;
    bottom: 0;
    left: 4rem;
    z-index: 3;
    padding: 0.5rem 0.2rem;
    border-radius: 1rem 1rem 0 0;
    background: #333;
  }

  .nav-search-1 .search-inactive.nav-search {
    display: none;
  }

  .nav-search-1 .search-activated.nav-search .highlight.nav-search,
  .nav-search-1 .search-activated.nav-search .search.nav-search {
    background: #fff;
    border-radius: 0.5rem;
  }

  .nav-search-1 .search-activated.nav-search .highlight.nav-search {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    width: 100%;
    margin: 0 0.5rem;
  }

  .nav-search-1 .search-activated.nav-search .search.nav-search {
    height: 100%;
    padding: 0;
    margin-right: 0;
    -ms-flex-item-align: center;
    -ms-grid-row-align: center;
    align-self: center;
  }

  .nav-search-1 .search-activated.nav-search .search.nav-search svg.nav-search {
    height: 3rem;
    width: 3rem;
  }

  .nav-search-1 .search-activated.nav-search .search-field.nav-search {
    width: 100%;
    height: 100%;
    box-sizing: border-box;
    padding-left: 1rem;
    border-radius: 0.5rem;
    border: none;
    font-size: 1.6rem;
    text-align: center;
  }

  .nav-search-1 .search-activated.nav-search .search-field.nav-search:focus {
    outline: none;
  }

  @keyframes fade-in-nav-search-1 {
    0% {
      opacity: 0;
    }

    100% {
      opacity: 1;
    }

  }

  .nav-search-1 .fade-in.nav-search {
    animation: fade-in-nav-search-1 0.2s forwards;
  }

  @media (min-width: 890px) {
    .nav-search-1 .search.nav-search svg.nav-search {
      display: inline;
      width: 2.8rem;
      height: 2.8rem;
      vertical-align: -14px;
    }

    .nav-search-1 .search.nav-search path.nav-search {
      fill: #333;
    }

    .nav-search-1 .search-inactive.nav-search,
    .nav-search-1 .search-activated.nav-search {
      display: block;
      position: static;
      padding: 1.1rem 0.2rem;
      background: transparent;
    }

    .nav-search-1 .search-activated.nav-search .highlight.nav-search {
      width: 13rem;
      height: 2.8rem;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: reverse;
      -ms-flex-direction: row-reverse;
      flex-direction: row-reverse;
    }

    .nav-search-1 .search-activated.nav-search .search-field.nav-search {
      width: calc(100% - 28px);
      height: 100%;
      padding-left: 0;
      font-size: 1.4rem;
      text-align: left;
    }

    .nav-search-1 .search-activated.nav-search .search.nav-search svg.nav-search {
      width: 2.8rem;
      height: 2.8rem;
    }

  }
    </style>
    <!-- Shady DOM styles for media-button -->
    <style scope="media-button-1">
     .media-button-1 a.media-button {
    display: inline-block;
    text-decoration: none;
  }

  .media-button-1 .menu-item.media-button {
    display: inline-block;
    width: 100%;
    padding: 0;
    font-size: 1.6rem;
    text-align: left;
    background: transparent;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
  }

  .media-button-1 .menu-item.media-button:focus {
    outline: none;
  }

  .media-button-1 .label.media-button {
    display: inline-block;
    padding: 0;
    font-weight: 400;
    color: #fff;
    text-align: left;
    vertical-align: middle;
  }

  .media-button-1 .menu-item.media-button>.icon.media-button {
    display: inline-flex;
    vertical-align: middle;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
  }

  .media-button-1 .menu-item.media-button>.icon.media-button>svg.media-button {
    height: 4rem;
    width: 4rem;
  }

  .media-button-1 .menu-item.selected.media-button .icon.media-button {
    background-color: #333;
    border-radius: 1rem 0 0 1rem;
  }

  .media-button-1 .icon.media-button .fill-color.media-button {
    fill: #999;
  }

  .media-button-1 .icon.active.media-button .fill-color.media-button {
    fill: #fff;
  }

  .media-button-1 .donate.media-button .fill-color.media-button {
    fill: #f00;
  }

  @media (min-width: 890px) {
    .media-button-1 .menu-item.media-button {
      width: auto;
      height: 5rem;
      color: #999;
      display: inline-flex;
    }

    .media-button-1 .menu-item.media-button:hover,
    .media-button-1 .menu-item.media-button:active,
    .media-button-1 .menu-item.media-button:focus {
      color: #fff;
    }

    .media-button-1 .menu-item.media-button:hover .fill-color.media-button,
    .media-button-1 .menu-item.media-button:active .fill-color.media-button,
    .media-button-1 .menu-item.media-button:focus .fill-color.media-button {
      fill: #fff;
    }

    .media-button-1 .label.media-button {
      display: none;
    }

    .media-button-1 .label.media-button,
    .media-button-1 .web.media-button:after {
      padding-right: 1rem;
      font-size: 1.3rem;
      text-transform: uppercase;
      color: inherit;
    }

    .media-button-1 .web.media-button:after {
      display: none;
      content: "web";
    }

    .media-button-1 .donate.media-button,
    .media-button-1 .more.media-button {
      display: none;
    }

    .media-button-1 .menu-item.selected.media-button {
      background: #474747;
    }

    .media-button-1 .menu-item.selected.media-button .label.media-button,
    .media-button-1 .menu-item.selected.web.media-button:after {
      color: #fff;
    }

    .media-button-1 .menu-item.selected.media-button .icon.media-button {
      background: transparent;
    }

    .media-button-1 .web.selected.media-button .fill-color.media-button {
      fill: #ffcd27;
    }

    .media-button-1 .texts.selected.media-button .fill-color.media-button {
      fill: #faab3c;
    }

    .media-button-1 .video.selected.media-button .fill-color.media-button {
      fill: #f1644b;
    }

    .media-button-1 .audio.selected.media-button .fill-color.media-button {
      fill: #00adef;
    }

    .media-button-1 .software.selected.media-button .fill-color.media-button {
      fill: #9ecc4f;
    }

    .media-button-1 .images.selected.media-button .fill-color.media-button {
      fill: #aa99c9;
    }

  }

  @media (min-width: 1200px) {

    .media-button-1 .label.media-button,
    .media-button-1 .web.media-button:after {
      display: inline;
    }

    .media-button-1 .web.media-button .label.media-button {
      display: none;
    }

  }
    </style>
    <!-- Shady DOM styles for media-menu -->
    <style scope="media-menu-1">
     .media-menu-1 {
    outline: none;
  }

  .media-menu-1 .media-menu-inner.media-menu {
    z-index: -1;
    top: -40rem;
    background-color: #222;
    margin: 0;
    overflow: hidden;
    transition-duration: 0.2s;
    transition-property: top;
    transition-timing-function: ease;
  }

  .media-menu-1 .menu-group.media-menu {
    position: relative;
    line-height: normal;
  }

  @media (max-width: 889px) {
    .media-menu-1 .media-menu-inner.media-menu {
      position: absolute;
      width: 100%;
    }

    .media-menu-1 .open.media-menu .media-menu-inner.media-menu {
      top: 0;
    }

    .media-menu-1 .overflow-clip.media-menu {
      position: absolute;
      z-index: -1;
      top: 4rem;
      left: 0;
      height: 0;
      width: 100%;
      overflow: hidden;
      transition-duration: 0.2s;
      transition-property: height;
    }

    .media-menu-1 .open.media-menu .overflow-clip.media-menu {
      height: 40rem;
    }

  }


In [88]:
# What is the username?
username = soup.find("a", class_="item-upload-info__uploader-name")
username = username.text.strip()

In [84]:
# How many pages?
numPages = soup.find("span", itemprop="numberOfPages")

In [90]:
numPages = numPages.text.strip()

In [91]:
# Test 
assert username == 'hank_b'
assert numPages == '418'

### Reading from SQL

In [93]:
import pandas as pd
from sqlalchemy import create_engine, text

In [95]:
df = pd.read_csv('bestofrt.csv')

In [96]:
df.head(3)

,ranking,title,critic_score,number_of_critic_ratings,audience_score,number_of_audience_ratings,review_url,review_text,poster_url
0,1,The Wizard of Oz (1939),99,110,89,874425,http://www.rogerebert.com/reviews/great-movie-...,As a child I simply did not notice whether a m...,https://upload.wikimedia.org/wikipedia/commons...
1,2,Citizen Kane (1941),100,75,90,157274,http://www.rogerebert.com/reviews/great-movie-...,“I don't think any word can explain a man's li...,https://upload.wikimedia.org/wikipedia/en/c/ce...
2,3,The Third Man (1949),100,77,93,53081,http://www.rogerebert.com/reviews/great-movie-...,Has there ever been a film where the music mor...,https://upload.wikimedia.org/wikipedia/en/2/21...

In [97]:
# Connect to DB

engine = create_engine('sqlite:///movies.db')

In [ ]:
# storing the csv data in the db
df.to_sql('movies',engine,index=False,if_exists='replace')

89

In [ ]:
# Reading the data / querying
df_gather = pd.read_sql(sql=text('SELECT * FROM movies'), con=engine.connect())

In [100]:
df_gather.head(3)

,ranking,title,critic_score,number_of_critic_ratings,audience_score,number_of_audience_ratings,review_url,review_text,poster_url
0,1,The Wizard of Oz (1939),99,110,89,874425,http://www.rogerebert.com/reviews/great-movie-...,As a child I simply did not notice whether a m...,https://upload.wikimedia.org/wikipedia/commons...
1,2,Citizen Kane (1941),100,75,90,157274,http://www.rogerebert.com/reviews/great-movie-...,“I don't think any word can explain a man's li...,https://upload.wikimedia.org/wikipedia/en/c/ce...
2,3,The Third Man (1949),100,77,93,53081,http://www.rogerebert.com/reviews/great-movie-...,Has there ever been a film where the music mor...,https://upload.wikimedia.org/wikipedia/en/2/21...

Hospital Dataset Practice

In [101]:
import requests
from bs4 import BeautifulSoup
import json
import pandas as pd

In [102]:
#Extract data via API
response = requests.get('https://data.chhs.ca.gov/api/3/action/datastore_search?resource_id=d97adf28-ebaf-4204-a29e-bb6bdb7f96b9')

#Raise an exception if we made a request resulting in an error
response.raise_for_status()
#Get the JSON
data = response.json()
data

{'help': 'https://data.chhs.ca.gov/api/3/action/help_show?name=datastore_search',
 'success': True,
 'result': {'include_total': True,
  'limit': 100,
  'records_format': 'objects',
  'resource_id': 'd97adf28-ebaf-4204-a29e-bb6bdb7f96b9',
  'total_estimation_threshold': None,
  'records': [{'_id': 1,
    'County Code': '01 - Alameda',
    'Perm ID': '11210',
    'Facility Name': 'Alameda Hospital',
    'City': 'Alameda',
    'Building Nbr': 'BLD-01278',
    'Building Name': 'Original Hospital',
    'Building Status': 'OSHPD 1R-No Gen Acute Care - OSHPD Bldg',
    'SPC Rating *': 'N/A',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=26HIS&capID2=00000&capID3=00002&agencyCode=OSHPD',
    'Height (ft)': '44.17',
    'Stories': '4',
    'Building Code': 'Unknown',
    'Building Code Year': None,
    'Year Completed': '1926',
    'AB 1882 Notice': None,
    'Latitude': '37.7626572',
    'Longitude': '-122.2538986',
    'Count': '1'},
   {'_id': 2,
    'County Code': '01 - Alameda',
    'Perm ID': '11210',
    'Facility Name': 'Alameda Hospital',
    'City': 'Alameda',
    'Building Nbr': 'BLD-01279',
    'Building Name': 'Stephens Wing',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=56HIS&capID2=00000&capID3=00012&agencyCode=OSHPD',
    'Height (ft)': '35',
    'Stories': '3',
    'Building Code': '1952 Uniform Building Code (UBC)',
    'Building Code Year': '1952',
    'Year Completed': '1956',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.7626572',
    'Longitude': '-122.2538986',
    'Count': '1'},
   {'_id': 3,
    'County Code': '01 - Alameda',
    'Perm ID': '11210',
    'Facility Name': 'Alameda Hospital',
    'City': 'Alameda',
    'Building Nbr': 'BLD-01280',
    'Building Name': 'West Wing',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=68HIS&capID2=00000&capID3=00036&agencyCode=OSHPD',
    'Height (ft)': None,
    'Stories': '2',
    'Building Code': '1964 Uniform Building Code (UBC)',
    'Building Code Year': '1964',
    'Year Completed': '1968',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.7626572',
    'Longitude': '-122.2538986',
    'Count': '1'},
   {'_id': 4,
    'County Code': '01 - Alameda',
    'Perm ID': '11210',
    'Facility Name': 'Alameda Hospital',
    'City': 'Alameda',
    'Building Nbr': 'BLD-01281',
    'Building Name': 'South Wing',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '3s',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=83HIS&capID2=00000&capID3=00027&agencyCode=OSHPD',
    'Height (ft)': None,
    'Stories': '3',
    'Building Code': '1976 California Building Code (CBC)',
    'Building Code Year': '1976',
    'Year Completed': '1983',
    'AB 1882 Notice': None,
    'Latitude': '37.7626572',
    'Longitude': '-122.2538986',
    'Count': '1'},
   {'_id': 5,
    'County Code': '01 - Alameda',
    'Perm ID': '11210',
    'Facility Name': 'Alameda Hospital',
    'City': 'Alameda',
    'Building Nbr': 'BLD-01282',
    'Building Name': 'Radiology Addition',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '4',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=95HIS&capID2=00000&capID3=00031&agencyCode=OSHPD',
    'Height (ft)': '27',
    'Stories': '2',
    'Building Code': '1985 California Building Code (CBC)',
    'Building Code Year': '1985',
    'Year Completed': '1995',
    'AB 1882 Notice': None,
    'Latitude': '37.7626572',
    'Longitude': '-122.2538986',
    'Count': '1'},
   {'_id': 6,
    'County Code': '01 - Alameda',
    'Perm ID': '11210',
    'Facility Name': 'Alameda Hospital',
    'City': 'Alameda',
    'Building Nbr': 'BLD-01283',
    'Building Name': 'Medical Gas Storage',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '3',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=95HIS&capID2=00000&capID3=00032&agencyCode=OSHPD',
    'Height (ft)': '8.42',
    'Stories': '1',
    'Building Code': '1985 California Building Code (CBC)',
    'Building Code Year': '1985',
    'Year Completed': '1995',
    'AB 1882 Notice': None,
    'Latitude': '37.7626572',
    'Longitude': '-122.2538986',
    'Count': '1'},
   {'_id': 7,
    'County Code': '01 - Alameda',
    'Perm ID': '11210',
    'Facility Name': 'Alameda Hospital',
    'City': 'Alameda',
    'Building Nbr': 'BLD-02630',
    'Building Name': 'Compactor Shed',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '4',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=83HIS&capID2=00000&capID3=00048&agencyCode=OSHPD',
    'Height (ft)': None,
    'Stories': '1',
    'Building Code': '1976 California Building Code (CBC)',
    'Building Code Year': '1976',
    'Year Completed': '1983',
    'AB 1882 Notice': None,
    'Latitude': '37.7626572',
    'Longitude': '-122.2538986',
    'Count': '1'},
   {'_id': 8,
    'County Code': '01 - Alameda',
    'Perm ID': '11210',
    'Facility Name': 'Alameda Hospital',
    'City': 'Alameda',
    'Building Nbr': 'BLD-03120',
    'Building Name': 'Emergency Room Relocation',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '3s',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=87HIS&capID2=00000&capID3=00045&agencyCode=OSHPD',
    'Height (ft)': None,
    'Stories': '1',
    'Building Code': '1979 California Building Code (CBC)',
    'Building Code Year': '1979',
    'Year Completed': '1988',
    'AB 1882 Notice': None,
    'Latitude': '37.7626572',
    'Longitude': '-122.2538986',
    'Count': '1'},
   {'_id': 9,
    'County Code': '01 - Alameda',
    'Perm ID': '11210',
    'Facility Name': 'Alameda Hospital',
    'City': 'Alameda',
    'Building Nbr': 'BLD-05597',
    'Building Name': 'LOX Tank',
    'Building Status': 'OSHPD 1-Equipment Yard',
    'SPC Rating *': 'N/A',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=13CAP&capID2=00000&capID3=003TM&agencyCode=OSHPD',
    'Height (ft)': None,
    'Stories': None,
    'Building Code': '2010 California Building Code (CBC)',
    'Building Code Year': '2010',
    'Year Completed': '2016',
    'AB 1882 Notice': None,
    'Latitude': '37.7626572',
    'Longitude': '-122.2538986',
    'Count': '1'},
   {'_id': 10,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00695',
    'Building Name': 'Ehman Building',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=37HIS&capID2=00000&capID3=00001&agencyCode=OSHPD',
    'Height (ft)': '49.75',
    'Stories': '4',
    'Building Code': '1927 Uniform Building Code (UBC)',
    'Building Code Year': '1927',
    'Year Completed': '1937',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 11,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00696',
    'Building Name': 'North Wing',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=52HIS&capID2=00000&capID3=00004&agencyCode=OSHPD',
    'Height (ft)': '50',
    'Stories': '4',
    'Building Code': '1946 Uniform Building Code (UBC)',
    'Building Code Year': '1946',
    'Year Completed': '1952',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 12,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00698',
    'Building Name': 'East Wing',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=64HIS&capID2=00000&capID3=00015&agencyCode=OSHPD',
    'Height (ft)': '62.5',
    'Stories': '5',
    'Building Code': '1961 Uniform Building Code (UBC)',
    'Building Code Year': '1961',
    'Year Completed': '1964',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 13,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00699',
    'Building Name': 'Original West Wing',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=45HIS&capID2=00000&capID3=00001&agencyCode=OSHPD',
    'Height (ft)': '36',
    'Stories': '3',
    'Building Code': '1943 Uniform Building Code (UBC)',
    'Building Code Year': '1943',
    'Year Completed': '1945',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 14,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00700',
    'Building Name': 'West Service Wing - Building 1',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=64HIS&capID2=00000&capID3=00016&agencyCode=OSHPD',
    'Height (ft)': '33.3',
    'Stories': '3',
    'Building Code': '1961 Uniform Building Code (UBC)',
    'Building Code Year': '1961',
    'Year Completed': '1965',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 15,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00701',
    'Building Name': 'Physio-Therapy Building',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=60HIS&capID2=00000&capID3=00012&agencyCode=OSHPD',
    'Height (ft)': '12',
    'Stories': '1',
    'Building Code': '1952 Uniform Building Code (UBC)',
    'Building Code Year': '1952',
    'Year Completed': '1960',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 16,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00702',
    'Building Name': 'Original Emergency Wing',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=60HIS&capID2=00000&capID3=00013&agencyCode=OSHPD',
    'Height (ft)': '12',
    'Stories': '1',
    'Building Code': '1952 Uniform Building Code (UBC)',
    'Building Code Year': '1952',
    'Year Completed': '1960',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 17,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00703',
    'Building Name': 'Special Procedures Addition',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '3',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=74HIS&capID2=00000&capID3=00012&agencyCode=OSHPD',
    'Height (ft)': None,
    'Stories': '1',
    'Building Code': '1973 California Building Code (CBC)',
    'Building Code Year': '1973',
    'Year Completed': '1974',
    'AB 1882 Notice': None,
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 18,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00704',
    'Building Name': 'Emergency Department Expansion',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '5s',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=01HIS&capID2=00000&capID3=00013&agencyCode=OSHPD',
    'Height (ft)': None,
    'Stories': '1',
    'Building Code': '1995 California Building Code (CBC)',
    'Building Code Year': '1995',
    'Year Completed': '2002',
    'AB 1882 Notice': None,
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 19,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00705',
    'Building Name': 'Cogeneration Building',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '4',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=90HIS&capID2=00000&capID3=00024&agencyCode=OSHPD',
    'Height (ft)': '11.75',
    'Stories': '1',
    'Building Code': '1982 California Building Code (CBC)',
    'Building Code Year': '1982',
    'Year Completed': '1990',
    'AB 1882 Notice': None,
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 20,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00706',
    'Building Name': 'Emergency Generator Building',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '4',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=80HIS&capID2=00000&capID3=00499&agencyCode=OSHPD',
    'Height (ft)': None,
    'Stories': '2',
    'Building Code': '1973 California Building Code (CBC)',
    'Building Code Year': '1973',
    'Year Completed': '1982',
    'AB 1882 Notice': None,
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 21,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-00707',
    'Building Name': 'Transformer Building',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '2',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=69HIS&capID2=00000&capID3=00013&agencyCode=OSHPD',
    'Height (ft)': '21.7',
    'Stories': '2',
    'Building Code': '1967 Uniform Building Code (UBC)',
    'Building Code Year': '1967',
    'Year Completed': '1969',
    'AB 1882 Notice': 'This building does not significantly jeopardize life, but may not be repairable or functional following an earthquake.',
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 22,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-03431',
    'Building Name': 'South Wing - Phase 2',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '3',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=78HIS&capID2=00000&capID3=00055&agencyCode=OSHPD',
    'Height (ft)': '102.5',
    'Stories': '6',
    'Building Code': '1973 California Building Code (CBC)',
    'Building Code Year': '1973',
    'Year Completed': '1980',
    'AB 1882 Notice': None,
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 23,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-03433',
    'Building Name': 'West Service Wing - Building 2 - Structurally connected to BLD-00699',
    'Building Status': 'OSHPD 1-Not an Independent Building',
    'SPC Rating *': 'N/A',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=64HIS&capID2=00000&capID3=00062&agencyCode=OSHPD',
    'Height (ft)': '23',
    'Stories': '2',
    'Building Code': '1961 Uniform Building Code (UBC)',
    'Building Code Year': '1961',
    'Year Completed': '1965',
    'AB 1882 Notice': None,
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 24,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-03434',
    'Building Name': 'Orig Emergency Wing - East Wing - Structurally connected to BLD-00702',
    'Building Status': 'OSHPD 1-Not an Independent Building',
    'SPC Rating *': 'N/A',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=64HIS&capID2=00000&capID3=00063&agencyCode=OSHPD',
    'Height (ft)': None,
    'Stories': '1',
    'Building Code': '1961 Uniform Building Code (UBC)',
    'Building Code Year': '1961',
    'Year Completed': '1964',
    'AB 1882 Notice': None,
    'Latitude': '37.8208094',
    'Longitude': '-122.2630806',
    'Count': '1'},
   {'_id': 25,
    'County Code': '01 - Alameda',
    'Perm ID': '11322',
    'Facility Name': 'Alta Bates Summit Medical Center',
    'City': 'Oakland',
    'Building Nbr': 'BLD-05300',
    'Building Name': 'Patient Care Pavilion',
    'Building Status': 'OSHPD 1-In Service',
    'SPC Rating *': '5',
    'Building URL': 'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=11CAP&capID2=00000&capID3=0034R&agencyCode=OSHPD',
    'Height (ft)': '154.75',
    'Stories': '12',
    'Building Code': '2007 California Building Code (CBC)',
    'Building Code Year': '2007',

In [ ]:
# Getting data from the json response 
relevance = data["result"]["records"][0]["City"]

In [ ]:
# City 
relevance

'Alameda'

In [105]:
data_list = []

with open('hospital_building_data.csv') as hbd:
    for line in hbd:
        data_list.append(line.rstrip('\n').split(','))

In [106]:
data_list

[['ï»¿County Code',
  'Perm ID',
  'Facility Name',
  'City',
  'Building Nbr',
  'Building Name',
  'Building Status',
  'SPC Rating *',
  'Building URL',
  'Height (ft)',
  'Stories',
  'Building Code',
  'Building Code Year',
  'Year Completed',
  'AB 1882 Notice',
  'Latitude',
  'Longitude',
  'Count'],
 ['01 - Alameda',
  '11210',
  'Alameda Hospital',
  'Alameda',
  'BLD-01278',
  'Original Hospital',
  'No Gen Acute Care - OSHPD Bldg',
  'N/A',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=26HIS&capID2=00000&capID3=00002&agencyCode=OSHPD',
  '44.17',
  '4',
  'Unknown',
  '',
  '1926',
  '',
  '37.7626572',
  '-122.2538986',
  '1'],
 ['01 - Alameda',
  '11210',
  'Alameda Hospital',
  'Alameda',
  'BLD-01279',
  'Stephens Wing',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=56HIS&capID2=00000&capID3=00012&agencyCode=OSHPD',
  '35',
  '3',
  '1952 Uniform Building Code (UBC)',
  '1952',
  '1956',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.7626572',
  '-122.2538986',
  '1'],
 ['01 - Alameda',
  '11210',
  'Alameda Hospital',
  'Alameda',
  'BLD-01280',
  'West Wing',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=68HIS&capID2=00000&capID3=00036&agencyCode=OSHPD',
  '',
  '2',
  '1964 Uniform Building Code (UBC)',
  '1964',
  '1968',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.7626572',
  '-122.2538986',
  '1'],
 ['01 - Alameda',
  '11210',
  'Alameda Hospital',
  'Alameda',
  'BLD-01281',
  'South Wing',
  'In Service',
  '3s',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=83HIS&capID2=00000&capID3=00027&agencyCode=OSHPD',
  '',
  '3',
  '1976 California Building Code (CBC)',
  '1976',
  '1983',
  '',
  '37.7626572',
  '-122.2538986',
  '1'],
 ['01 - Alameda',
  '11210',
  'Alameda Hospital',
  'Alameda',
  'BLD-01282',
  'Radiology Addition',
  'In Service',
  '5s',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=95HIS&capID2=00000&capID3=00031&agencyCode=OSHPD',
  '',
  '2',
  '1985 California Building Code (CBC)',
  '1985',
  '1995',
  '',
  '37.7626572',
  '-122.2538986',
  '1'],
 ['01 - Alameda',
  '11210',
  'Alameda Hospital',
  'Alameda',
  'BLD-01283',
  'Medical Gas Storage',
  'In Service',
  '3',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=95HIS&capID2=00000&capID3=00032&agencyCode=OSHPD',
  '8.42',
  '1',
  '1985 California Building Code (CBC)',
  '1985',
  '1995',
  '',
  '37.7626572',
  '-122.2538986',
  '1'],
 ['01 - Alameda',
  '11210',
  'Alameda Hospital',
  'Alameda',
  'BLD-02630',
  'Compactor Shed',
  'In Service',
  '4',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=83HIS&capID2=00000&capID3=00048&agencyCode=OSHPD',
  '',
  '1',
  '1976 California Building Code (CBC)',
  '1976',
  '1983',
  '',
  '37.7626572',
  '-122.2538986',
  '1'],
 ['01 - Alameda',
  '11210',
  'Alameda Hospital',
  'Alameda',
  'BLD-03120',
  'Emergency Room Relocation',
  'In Service',
  '3s',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=87HIS&capID2=00000&capID3=00045&agencyCode=OSHPD',
  '',
  '1',
  '1979 California Building Code (CBC)',
  '1979',
  '1988',
  '',
  '37.7626572',
  '-122.2538986',
  '1'],
 ['01 - Alameda',
  '11210',
  'Alameda Hospital',
  'Alameda',
  'BLD-05597',
  'LOX Tank',
  'Under Construction',
  'N/A',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=13CAP&capID2=00000&capID3=003TM&agencyCode=OSHPD',
  '',
  '',
  '2010 California Building Code (CBC)',
  '2010',
  '2016',
  '',
  '37.7626572',
  '-122.2538986',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00695',
  'Ehman Building',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=37HIS&capID2=00000&capID3=00001&agencyCode=OSHPD',
  '49.75',
  '4',
  '1927 Uniform Building Code (UBC)',
  '1927',
  '1937',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00696',
  'North Wing',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=52HIS&capID2=00000&capID3=00004&agencyCode=OSHPD',
  '50',
  '4',
  '1946 Uniform Building Code (UBC)',
  '1946',
  '1952',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00698',
  'East Wing',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=64HIS&capID2=00000&capID3=00015&agencyCode=OSHPD',
  '62.5',
  '5',
  '1961 Uniform Building Code (UBC)',
  '1961',
  '1964',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00699',
  'Original West Wing',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=45HIS&capID2=00000&capID3=00001&agencyCode=OSHPD',
  '36',
  '3',
  '1943 Uniform Building Code (UBC)',
  '1943',
  '1945',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00700',
  'West Service Wing - Building 1',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=64HIS&capID2=00000&capID3=00016&agencyCode=OSHPD',
  '33.3',
  '3',
  '1961 Uniform Building Code (UBC)',
  '1961',
  '1965',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00701',
  'Physio-Therapy Building',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=60HIS&capID2=00000&capID3=00012&agencyCode=OSHPD',
  '12',
  '1',
  '1952 Uniform Building Code (UBC)',
  '1952',
  '1960',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00702',
  'Original Emergency Wing',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=60HIS&capID2=00000&capID3=00013&agencyCode=OSHPD',
  '12',
  '1',
  '1952 Uniform Building Code (UBC)',
  '1952',
  '1960',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00703',
  'Special Procedures Addition',
  'In Service',
  '3',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=74HIS&capID2=00000&capID3=00012&agencyCode=OSHPD',
  '',
  '1',
  '1973 California Building Code (CBC)',
  '1973',
  '1974',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00704',
  'Emergency Department Expansion',
  'In Service',
  '5s',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=01HIS&capID2=00000&capID3=00013&agencyCode=OSHPD',
  '',
  '1',
  '1995 California Building Code (CBC)',
  '1995',
  '2002',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00705',
  'Cogeneration Building',
  'In Service',
  '4',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=90HIS&capID2=00000&capID3=00024&agencyCode=OSHPD',
  '11.75',
  '1',
  '1982 California Building Code (CBC)',
  '1982',
  '1990',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00706',
  'Emergency Generator Building',
  'In Service',
  '4',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=80HIS&capID2=00000&capID3=00499&agencyCode=OSHPD',
  '',
  '2',
  '1973 California Building Code (CBC)',
  '1973',
  '1982',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-00707',
  'Transformer Building',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=69HIS&capID2=00000&capID3=00013&agencyCode=OSHPD',
  '21.7',
  '2',
  '1967 Uniform Building Code (UBC)',
  '1967',
  '1969',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-03431',
  'South Wing - Phase 2',
  'In Service',
  '3',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=78HIS&capID2=00000&capID3=00055&agencyCode=OSHPD',
  '102.5',
  '6',
  '1973 California Building Code (CBC)',
  '1973',
  '1980',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-03433',
  'West Service Wing - Building 2 - Structurally connected to BLD-00699',
  'Not an Independent Building',
  'N/A',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=64HIS&capID2=00000&capID3=00062&agencyCode=OSHPD',
  '23',
  '2',
  '1961 Uniform Building Code (UBC)',
  '1961',
  '1965',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-03434',
  'Orig Emergency Wing - East Wing - Structurally connected to BLD-00702',
  'Not an Independent Building',
  'N/A',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=64HIS&capID2=00000&capID3=00063&agencyCode=OSHPD',
  '',
  '1',
  '1961 Uniform Building Code (UBC)',
  '1961',
  '1964',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-05300',
  'Patient Care Pavilion',
  'In Service',
  '5',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=11CAP&capID2=00000&capID3=0034R&agencyCode=OSHPD',
  '154.75',
  '12',
  '2007 California Building Code (CBC)',
  '2007',
  '2014',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-06010',
  'New LOX Tank',
  'Equipment Yard',
  'N/A',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=16CAP&capID2=00000&capID3=0023T&agencyCode=OSHPD',
  '',
  '',
  '2013 California Building Code (CBC)',
  '2013',
  '2019',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11322',
  'Alta Bates Summit Medical Center',
  'Oakland',
  'BLD-06060',
  'Emergency Generator Yard',
  'Equipment Yard',
  'N/A',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=16CAP&capID2=00000&capID3=004UR&agencyCode=OSHPD',
  '',
  '',
  '2007 California Building Code (CBC)',
  '2007',
  '2014',
  '',
  '37.8208094',
  '-122.2630806',
  '1'],
 ['01 - Alameda',
  '11338',
  'Alta Bates Summit Medical Center - Summit Campus',
  'Oakland',
  'BLD-00708',
  'Main Hospital Building',
  'In Service',
  '3',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=78HIS&capID2=00000&capID3=00013&agencyCode=OSHPD',
  '',
  '6',
  '1976 California Building Code (CBC)',
  '1976',
  '1978',
  '',
  '37.8199008',
  '-122.2643586',
  '1'],
 ['01 - Alameda',
  '11338',
  'Alta Bates Summit Medical Center - Summit Campus',
  'Oakland',
  'BLD-03443',
  'Main Entrance Canopy',
  'In Service',
  '3',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=78HIS&capID2=00000&capID3=00057&agencyCode=OSHPD',
  '',
  '1',
  '1976 California Building Code (CBC)',
  '1976',
  '1978',
  '',
  '37.8199008',
  '-122.2643586',
  '1'],
 ['01 - Alameda',
  '11338',
  'Alta Bates Summit Medical Center - Summit Campus',
  'Oakland',
  'BLD-03444',
  'Bridge at Link',
  'In Service',
  '3',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=78HIS&capID2=00000&capID3=00058&agencyCode=OSHPD',
  '',
  '2',
  '1976 California Building Code (CBC)',
  '1976',
  '1978',
  '',
  '37.8199008',
  '-122.2643586',
  '1'],
 ['01 - Alameda',
  '11214',
  'Alta Bates Summit Medical Center-Alta Bates Campus',
  'Berkeley',
  'BLD-01285',
  'Admin.',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=59HIS&capID2=00000&capID3=00011&agencyCode=OSHPD',
  '13',
  '1',
  '1955 Uniform Building Code (UBC)',
  '1955',
  '1959',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8559265',
  '-122.257309',
  '1'],
 ['01 - Alameda',
  '11214',
  'Alta Bates Summit Medical Center-Alta Bates Campus',
  'Berkeley',
  'BLD-01286',
  'Laundry/Hall of Health',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=59HIS&capID2=00000&capID3=00012&agencyCode=OSHPD',
  '25',
  '2',
  '1955 Uniform Building Code (UBC)',
  '1955',
  '1959',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8559265',
  '-122.257309',
  '1'],
 ['01 - Alameda',
  '11214',
  'Alta Bates Summit Medical Center-Alta Bates Campus',
  'Berkeley',
  'BLD-01287',
  'Boiler',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=68HIS&capID2=00000&capID3=00037&agencyCode=OSHPD',
  '25',
  '1',
  '1961 Uniform Building Code (UBC)',
  '1961',
  '1968',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8559265',
  '-122.257309',
  '1'],
 ['01 - Alameda',
  '11214',
  'Alta Bates Summit Medical Center-Alta Bates Campus',
  'Berkeley',
  'BLD-01288',
  '1968 Building',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=68HIS&capID2=00000&capID3=00038&agencyCode=OSHPD',
  '83',
  '7',
  '1961 Uniform Building Code (UBC)',
  '1961',
  '1968',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8559265',
  '-122.257309',
  '1'],
 ['01 - Alameda',
  '11214',
  'Alta Bates Summit Medical Center-Alta Bates Campus',
  'Berkeley',
  'BLD-01289',
  '1975 Building',
  'In Service',
  '2',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=75HIS&capID2=00000&capID3=00026&agencyCode=OSHPD',
  '67',
  '6',
  '1970 Uniform Building Code (UBC)',
  '1970',
  '1975',
  '"This building does not significantly jeopardize life',
  ' but may not be repairable or functional following an earthquake."',
  '37.8559265',
  '-122.257309',
  '1'],
 ['01 - Alameda',
  '11214',
  'Alta Bates Summit Medical Center-Alta Bates Campus',
  'Berkeley',
  'BLD-01290',
  '1985 Building',
  'In Service',
  '4',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=85HIS&capID2=00000&capID3=00017&agencyCode=OSHPD',
  '',
  '2',
  '1979 California Building Code (CBC)',
  '1979',
  '1988',
  '',
  '37.8559265',
  '-122.257309',
  '1'],
 ['01 - Alameda',
  '11214',
  'Alta Bates Summit Medical Center-Alta Bates Campus',
  'Berkeley',
  'BLD-01291',
  'Electric Service Building',
  'In Service',
  '4',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=85HIS&capID2=00000&capID3=00018&agencyCode=OSHPD',
  '',
  '2',
  '1979 California Building Code (CBC)',
  '1979',
  '1988',
  '',
  '37.8559265',
  '-122.257309',
  '1'],
 ['01 - Alameda',
  '11214',
  'Alta Bates Summit Medical Center-Alta Bates Campus',
  'Berkeley',
  'BLD-01292',
  'Oxygen Tank Enclosure',
  'Equipment Yard',
  'N/A',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=85HIS&capID2=00000&capID3=00019&agencyCode=OSHPD',
  '',
  '1',
  '1979 California Building Code (CBC)',
  '1979',
  '1988',
  '',
  '37.8559265',
  '-122.257309',
  '1'],
 ['01 - Alameda',
  '18180',
  'Eden Medical Center',
  'Castro Valley',
  'BLD-05340',
  'Replacement Hospital',
  'In Service',
  '5',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=12CAP&capID2=00000&capID3=001A5&agencyCode=OSHPD',
  '117.5',
  '6',
  '2007 California Building Code (CBC)',
  '2007',
  '2014',
  '',
  '37.69838',
  '-122.0873925',
  '1'],
 ['01 - Alameda',
  '18180',
  'Eden Medical Center',
  'Castro Valley',
  'BLD-05341',
  'Chiller Building',
  'In Service',
  '5',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=12CAP&capID2=00000&capID3=001A6&agencyCode=OSHPD',
  '18',
  '1',
  '2007 California Building Code (CBC)',
  '2007',
  '2014',
  '',
  '37.69838',
  '-122.0873925',
  '1'],
 ['01 - Alameda',
  '18180',
  'Eden Medical Center',
  'Castro Valley',
  'BLD-05342',
  'Main Entrance Canopy',
  'In Service',
  '5',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=12CAP&capID2=00000&capID3=001A7&agencyCode=OSHPD',
  '17',
  '1',
  '2007 California Building Code (CBC)',
  '2007',
  '2014',
  '',
  '37.69838',
  '-122.0873925',
  '1'],
 ['01 - Alameda',
  '18180',
  'Eden Medical Center',
  'Castro Valley',
  'BLD-05343',
  'Emergency Entrance Canopy',
  'In Service',
  '5',
  'https://esp.oshpd.ca.gov/CitizenAccess/Cap/CapDetail.aspx?Module=Permits&TabName=Permits&capID1=12CAP&capID2=00000&capID3=001A8&agencyCode=OSHPD',
  '17',
  '1',
  '2007 California Building Code (CBC)',
  '2007',
  '2014',
  '',
  '37.69838',
  '-122.0873925',
  '1'],
 ['01 - Alameda',
  '11268',
  'Fairmont Hospital',
  'San Leandro',
  'BLD-01311',
  'Building B',
  'Skilled Nursing Only',
  'N/A',

In [108]:
data_list[1][3]

'Alameda'