In [1]:
import pandas as pd
import numpy as np

### OEWS data (uncleaned)

The OEWS dataset was gathered manually as a CSV from the U.S. Bureau of Labor Statistics' website. The data was narrowed down to specifically focus on the managerial domain.

The dataset has a number of variables - there are four variables of significance to us:

- AREA_TITLE: Area/location name, e.g. Alabama
- OCC_CODE: The Standard Occupational Classification (SOC) code, e.g. 11-0000
- OCC_TITLE: The Standard Occupational Classification (SOC) title, e.g. Management Occupations
- H_MEAN: The mean hourly wage of the worker, e.g. 61.13

### PUMS data (cleaned)

The PUMS dataset was downloaded via the Census Data API from the United Statest Census Bureau, and narrowed down for the Kern County - Bakersfield MSA, California area.

Dataset variables and values:

- WRK: Whether the individual worked last week
    - 0: N/A (not reported)
    - 1: Worked
    - 2: Did not work
- SEX: Sex (Male / Female) of the individual
    - 1: Male
    - 2: Female 
- SCOP: Standard Occupational Classification (SOC) codes for 2018 and later, based on the 2018 SOC codes

In [7]:
oews_data = pd.read_excel('Research.xlsx')

oews_data.head()

,AREA,AREA_TITLE,NAICS,NAICS_TITLE,I_GROUP,OCC_CODE,OCC_TITLE,O_GROUP,TOT_EMP,EMP_PRSE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,1,Alabama,55,Management of Companies and Enterprises,sector,00-0000,All Occupations,total,21920,0,...,35.6,56.94,79.49,35470,47040,74050,118440,165330,NaN,NaN
1,1,Alabama,55,Management of Companies and Enterprises,sector,11-0000,Management Occupations,major,4820,4.1,...,61.13,92.03,#,61600,94020,127140,191420,#,NaN,NaN
2,1,Alabama,55,Management of Companies and Enterprises,sector,11-1021,General and Operations Managers,detailed,1600,7,...,60.5,#,#,60010,78520,125850,#,#,NaN,NaN
3,1,Alabama,55,Management of Companies and Enterprises,sector,11-2021,Marketing Managers,detailed,140,13.6,...,61.13,99.23,#,65240,98680,127140,206410,#,NaN,NaN
4,1,Alabama,55,Management of Companies and Enterprises,sector,11-2022,Sales Managers,detailed,140,14.7,...,49.56,77.94,#,59390,79010,103080,162110,#,NaN,NaN

In [9]:
cleaned_pums = pd.read_csv('cleaned_pums_2021.csv')
cleaned_pums.sample(3)

       WRK  SEX    SOCP
8904     1    2  119151
8929     1    1  111021
19013    1    1  113021

In [11]:
oews_data_subset = oews_data[["AREA_TITLE", "OCC_CODE","OCC_TITLE","H_MEAN"]]
oews_data_subset.head()

  AREA_TITLE OCC_CODE                        OCC_TITLE H_MEAN
0    Alabama  00-0000                  All Occupations  42.88
1    Alabama  11-0000           Management Occupations   70.9
2    Alabama  11-1021  General and Operations Managers  72.76
3    Alabama  11-2021               Marketing Managers  69.97
4    Alabama  11-2022                   Sales Managers  62.97

In [14]:
oews_data_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71508 entries, 0 to 71507
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AREA_TITLE  71508 non-null  object
 1   OCC_CODE    71508 non-null  object
 2   OCC_TITLE   71508 non-null  object
 3   H_MEAN      71508 non-null  object
dtypes: object(4)
memory usage: 2.2+ MB

In [19]:
oews_data_subset.describe()

        AREA_TITLE OCC_CODE        OCC_TITLE H_MEAN
count        71508    71508            71508  71508
unique          54      596              596   6818
top     California  00-0000  All Occupations      *
freq          3223     1161             1161    536

In [20]:
oews_data_subset.dtypes

AREA_TITLE    object
OCC_CODE      object
OCC_TITLE     object
H_MEAN        object
dtype: object

In [22]:
pd.options.mode.chained_assignment = None

In [24]:
oews_data_subset['H_MEAN'] = oews_data_subset['H_MEAN'].replace({'*':np.nan})

In [25]:
oews_data_subset['H_MEAN'].describe()

count     70972.00
unique     6817.00
top          20.65
freq         57.00
Name: H_MEAN, dtype: float64

In [27]:
# Null values after fixing the inconsistent nulls in H_mean
oews_data_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71508 entries, 0 to 71507
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AREA_TITLE  71508 non-null  object
 1   OCC_CODE    71508 non-null  object
 2   OCC_TITLE   71508 non-null  object
 3   H_MEAN      70972 non-null  object
dtypes: object(4)
memory usage: 2.2+ MB

In [28]:
oews_data_subset.head()

  AREA_TITLE OCC_CODE                        OCC_TITLE H_MEAN
0    Alabama  00-0000                  All Occupations  42.88
1    Alabama  11-0000           Management Occupations   70.9
2    Alabama  11-1021  General and Operations Managers  72.76
3    Alabama  11-2021               Marketing Managers  69.97
4    Alabama  11-2022                   Sales Managers  62.97

In [29]:
cleaned_pums.head()

   WRK  SEX    SOCP
0    1    2  119151
1    2    1  119111
2    1    2  113121
3    1    1  1110XX
4    1    1  113051

Programatic Assessment

In [30]:
import pandas as pd